consul:
  container_name: consul
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  hostname: "registry"
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

api:
  container_name: api
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 --api_cors=* --enable_stats api
  image: microhq/micro
  links:
  - consul
  ports:
  - "8080:8080"

web:
  container_name: web
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  image: microhq/micro
  links:
  - consul
  ports:
  - "8082:8082"

elastic-api:
  container_name: elastic-api
  command: --registry_address=registry:8500
  build: api
  links:
    - consul

elastic-srv:
  container_name: elastic-srv
  command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
  build: srv
  links:
    - consul
    - elasticsearch

elasticsearch:
 container_name: elasticsearch
 image: elasticsearch:1.7.1
 hostname: "elasticsearch"
 ports:
   - "9200:9200"
   - "9300:9300"
 environment:
   ES_HEAP_SIZE: 512m
   ES_CLUSTER_NAME: Kazoup


