flag-api:
  container_name: flag-api
  command: --registry_address=registry:8500
  build: api
  external_links:
  - consul:registry

flag-srv:
  container_name: flag-srv
  command: --registry_address=registry:8500
  build: srv
  external_links:
  - consul:registry
