// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/audioenrich/srv/proto/audioenrich/audioenrich.proto
// DO NOT EDIT!

/*
Package go_micro_srv_audioenrich is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/audioenrich/srv/proto/audioenrich/audioenrich.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	HealthRequest
	HealthResponse
*/
package go_micro_srv_audioenrich

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HealthRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HealthResponse struct {
	Status int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.audioenrich.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.audioenrich.CreateResponse")
	proto.RegisterType((*HealthRequest)(nil), "go.micro.srv.audioenrich.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "go.micro.srv.audioenrich.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AudioEnrich service

type AudioEnrichClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
}

type audioEnrichClient struct {
	c           client.Client
	serviceName string
}

func NewAudioEnrichClient(serviceName string, c client.Client) AudioEnrichClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.audioenrich"
	}
	return &audioEnrichClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *audioEnrichClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AudioEnrich.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *audioEnrichClient) Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.serviceName, "AudioEnrich.Health", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AudioEnrich service

type AudioEnrichHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Health(context.Context, *HealthRequest, *HealthResponse) error
}

func RegisterAudioEnrichHandler(s server.Server, hdlr AudioEnrichHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AudioEnrich{hdlr}, opts...))
}

type AudioEnrich struct {
	AudioEnrichHandler
}

func (h *AudioEnrich) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.AudioEnrichHandler.Create(ctx, in, out)
}

func (h *AudioEnrich) Health(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.AudioEnrichHandler.Health(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/audioenrich/srv/proto/audioenrich/audioenrich.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 266 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x9b, 0x16, 0x22, 0x71, 0xa8, 0x11, 0xb2, 0x10, 0x8a, 0x98, 0x50, 0x18, 0xe8, 0x64,
	0x4b, 0xb0, 0xb2, 0x20, 0x84, 0x04, 0x0b, 0x43, 0x76, 0x06, 0x37, 0x71, 0x1b, 0x8b, 0x26, 0x67,
	0xec, 0x33, 0x02, 0xfe, 0x22, 0x7f, 0x8a, 0xc6, 0x49, 0xa5, 0x66, 0x20, 0xdd, 0x9e, 0xef, 0xee,
	0x3d, 0xbd, 0x4f, 0x86, 0xd7, 0xb5, 0xa6, 0xca, 0x2f, 0x79, 0x81, 0xb5, 0x78, 0x97, 0x3f, 0xe8,
	0x8d, 0x30, 0x1b, 0x49, 0x2b, 0xb4, 0xb5, 0x90, 0xbe, 0xd4, 0xa8, 0x1a, 0xab, 0x8b, 0x4a, 0x38,
	0xfb, 0x29, 0x8c, 0x45, 0xc2, 0xc1, 0x74, 0x4f, 0xf3, 0xb0, 0x65, 0xe9, 0x1a, 0x79, 0xad, 0x0b,
	0x8b, 0x7c, 0xeb, 0xe0, 0x7b, 0xfb, 0xec, 0x05, 0xe6, 0x8f, 0x56, 0x49, 0x52, 0xb9, 0xfa, 0xf0,
	0xca, 0x11, 0x63, 0x70, 0x44, 0xdf, 0x46, 0xa5, 0xd1, 0x55, 0xb4, 0x38, 0xc9, 0x83, 0x66, 0xe7,
	0x70, 0xac, 0x9b, 0x52, 0x7d, 0xa5, 0xd3, 0x30, 0xec, 0x1e, 0x2c, 0x81, 0xa9, 0x2e, 0xd3, 0x59,
	0x18, 0x6d, 0x55, 0x76, 0x06, 0xc9, 0x2e, 0xca, 0x19, 0x6c, 0x9c, 0xca, 0xae, 0x61, 0xfe, 0xac,
	0xe4, 0x86, 0xaa, 0x91, 0xf0, 0xec, 0x1e, 0x92, 0xdd, 0x51, 0x67, 0x63, 0x17, 0x10, 0x3b, 0x92,
	0xe4, 0x5d, 0xb8, 0x9b, 0xe5, 0xfd, 0xab, 0x75, 0xeb, 0x66, 0x85, 0x7d, 0x8b, 0xa0, 0x6f, 0x7f,
	0x23, 0x38, 0x7d, 0x68, 0x79, 0x9e, 0x02, 0x0f, 0x7b, 0x83, 0xb8, 0x2b, 0xc1, 0x6e, 0xf8, 0x7f,
	0xd0, 0x7c, 0x40, 0x7c, 0xb9, 0x38, 0x7c, 0xd8, 0xf3, 0x4c, 0xda, 0xf8, 0xae, 0xec, 0x58, 0xfc,
	0x80, 0x79, 0x2c, 0x7e, 0xc8, 0x9d, 0x4d, 0x96, 0x71, 0xf8, 0xae, 0xbb, 0xbf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x89, 0x93, 0x53, 0xb3, 0x00, 0x02, 0x00, 0x00,
}
