// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/scheduler/srv/proto/scheduler/scheduler.proto
// DO NOT EDIT!

/*
Package go_micro_srv_scheduler is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/scheduler/srv/proto/scheduler/scheduler.proto

It has these top-level messages:
	CreateScheduledTaskRequest
	CreateScheduledTaskResponse
*/
package go_micro_srv_scheduler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateScheduledTaskRequest struct {
}

func (m *CreateScheduledTaskRequest) Reset()                    { *m = CreateScheduledTaskRequest{} }
func (m *CreateScheduledTaskRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateScheduledTaskRequest) ProtoMessage()               {}
func (*CreateScheduledTaskRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateScheduledTaskResponse struct {
}

func (m *CreateScheduledTaskResponse) Reset()                    { *m = CreateScheduledTaskResponse{} }
func (m *CreateScheduledTaskResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateScheduledTaskResponse) ProtoMessage()               {}
func (*CreateScheduledTaskResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CreateScheduledTaskRequest)(nil), "go.micro.srv.scheduler.CreateScheduledTaskRequest")
	proto.RegisterType((*CreateScheduledTaskResponse)(nil), "go.micro.srv.scheduler.CreateScheduledTaskResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Scheduler service

type SchedulerClient interface {
	CreateScheduledTask(ctx context.Context, in *CreateScheduledTaskRequest, opts ...client.CallOption) (*CreateScheduledTaskResponse, error)
}

type schedulerClient struct {
	c           client.Client
	serviceName string
}

func NewSchedulerClient(serviceName string, c client.Client) SchedulerClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.scheduler"
	}
	return &schedulerClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *schedulerClient) CreateScheduledTask(ctx context.Context, in *CreateScheduledTaskRequest, opts ...client.CallOption) (*CreateScheduledTaskResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Scheduler.CreateScheduledTask", in)
	out := new(CreateScheduledTaskResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scheduler service

type SchedulerHandler interface {
	CreateScheduledTask(context.Context, *CreateScheduledTaskRequest, *CreateScheduledTaskResponse) error
}

func RegisterSchedulerHandler(s server.Server, hdlr SchedulerHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Scheduler{hdlr}, opts...))
}

type Scheduler struct {
	SchedulerHandler
}

func (h *Scheduler) CreateScheduledTask(ctx context.Context, in *CreateScheduledTaskRequest, out *CreateScheduledTaskResponse) error {
	return h.SchedulerHandler.CreateScheduledTask(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/scheduler/srv/proto/scheduler/scheduler.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xf2, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xac, 0xca, 0x2f, 0x2d, 0xd0, 0x2f, 0xc8,
	0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x2f, 0x4e, 0xce, 0x48, 0x4d, 0x29, 0xcd, 0x49, 0x2d,
	0xd2, 0x2f, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x47, 0x16, 0x83, 0xb1, 0xf4, 0xc0,
	0x32, 0x42, 0x62, 0xe9, 0xf9, 0x7a, 0xb9, 0x99, 0xc9, 0x45, 0xf9, 0x7a, 0x40, 0xd5, 0x7a, 0x70,
	0x59, 0x25, 0x19, 0x2e, 0x29, 0xe7, 0xa2, 0xd4, 0xc4, 0x92, 0xd4, 0x60, 0xa8, 0x50, 0x4a, 0x48,
	0x62, 0x71, 0x76, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x92, 0x2c, 0x97, 0x34, 0x56, 0xd9,
	0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0xa3, 0x3e, 0x46, 0x2e, 0x4e, 0x98, 0x4c, 0x91, 0x50, 0x03,
	0x23, 0x97, 0x30, 0x16, 0xd5, 0x42, 0x46, 0x7a, 0xd8, 0xed, 0xd6, 0xc3, 0x6d, 0xb1, 0x94, 0x31,
	0x49, 0x7a, 0x20, 0xce, 0x51, 0x62, 0x48, 0x62, 0x03, 0x7b, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff,
	0xff, 0x73, 0x83, 0xc8, 0xcb, 0x38, 0x01, 0x00, 0x00,
}
