elasticsearch:
 image: elasticsearch:2.3.4
 hostname: "elasticsearch"
 ports:
   - "9200:9200"
   - "9300:9300"
 environment:
   ES_HEAP_SIZE: 512m
   ES_CLUSTER_NAME: Kazoup

nats:
    image: 'nats:0.9.4'
    entrypoint: "/gnatsd -DV"
    expose:
      - "4222"
    ports:
      - "8222:8222"

registry:
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 --web_namespace=com.kazoup.web  --enable_stats=true  --selector=cache --enable_tls -tls_cert_file=/ssl/all.pem --tls_key_file=/ssl/key.pem web
  image: microhq/micro
  links:
  - registry
  ports:
  - "8082:8082"
  volumes:
  - "./cmd/kazoup/ssl:/ssl"


auth-web:
  command: --registry_address=registry:8500 --selector=cache
  image: kazoup/auth-web:latest
  links:
  - registry
  - nats


config-srv: 
  command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222
  image: kazoup/config-srv
  links:
  - registry
  - nats

config-web: 
  command: --registry_address=registry:8500 --selector=cache 
  image: kazoup/config-web
  links:
  - registry

crawler-srv:
   command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222
   image: kazoup/crawler-srv
   links:
   - registry
   - nats

datasource-srv:
  command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222
  image: kazoup/datasource-srv
  links:
  - registry
  - nats

db-srv:
  command: --elasticsearch_hosts=elasticsearch:9200 --registry_address=registry:8500  --selector=cache --broker=nats --broker_address=nats:4222
  image: kazoup/db-srv
  links:
  - registry
  - elasticsearch
  - nats
  
file-srv:
  command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222 --transport=tcp
  image: kazoup/flag-srv:latest
  links:
  - registry
  - nats

ui-web:
   command: --registry_address=registry:8500 --selector=cache 
   image : kazoup/desktop-web
   links:
   - registry
   - nats

flag-srv:
  command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222
  image: kazoup/flag-srv:latest
  links:
  - registry
  - nats

media-web:
  command: --registry_address=registry:8500 --selector=cache 
  image: kazoup/media-web:latest
  links:
  - registry
  - nats

search-srv:
  command: --registry_address=registry:8500 --selector=cache --broker=nats --broker_address=nats:4222
  image: kazoup/search-srv:latest
  links:
  - registry
  - nats

