elasticsearch:
 image: elasticsearch:2.3.4
 hostname: "elasticsearch"
 ports:
   - "9200:9200"
   - "9300:9300"
 environment:
   ES_HEAP_SIZE: 512m
   ES_CLUSTER_NAME: Kazoup

registry:
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  image: microhq/micro
  links:
  - registry
  ports:
  - "8082:8082"


auth-web:
  command: --registry_address=registry:8500
  image: kazoup/auth-web:latest
  links:
  - registry


config-srv:
  command: --registry_address=registry:8500
  image: kazoup/config-srv
  links:
  - registry

crawler-srv:
   command: --registry_address=registry:8500
   image: kazoup/crawler-srv
   volumes:
     - "/home/:/home"
   links:
   - registry

datasource-srv:
  command: --registry_address=registry:8500
  image: kazoup/datasource-srv
  links:
  - registry

db-srv:
  command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
  image: kazoup/db-srv
  links:
  - registry
  - elasticsearch

ui-srv:
  command: --registry_address=registry:8500
  image : kazoup/desktop-web
  links:
  - registry

flag-srv:
  command: --registry_address=registry:8500
  image: kazoup/flag-srv:latest
  links:
  - registry

media-web:
  command: --registry_address=registry:8500
  image: kazoup/media-web:latest
  links:
  - registry

search-srv:
  command: --registry_address=registry:8500
  image: kazoup/search-srv:latest
  links:
  - registry

