version: "2"
services:
        # Elastic service
        elastic-api:
          command: --registry_address=registry:8500
          image : kazoup/elastic-api
          links:
          - registry

        elastic-srv:
          command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
          image: kazoup/elastic-srv
          links:
          - elasticsearch
          - registry

        elasticsearch:
         image: elasticsearch:latest
         hostname: "elasticsearch"
         ports:
           - "9200:9200"
           - "9300:9300"
         environment:
           ES_HEAP_SIZE: 512m
           ES_CLUSTER_NAME: Kazoup

