# Micro
consul:
  container_name: consul
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  hostname: "registry"
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

api:
  container_name: api
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 --api_cors=* --enable_stats api
  image: microhq/micro
  links:
  - consul
  ports:
  - "8080:8080"

web:
  container_name: web
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  image: microhq/micro
  links:
  - consul
  ports:
  - "8082:8082"
# Elastic service
elastic-api:
  command: --registry_address=registry:8500
  image : kazoup/elastic-api
  links:
    - consul

elastic-srv:
  command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
  image: kazoup/elastic-srv
  links:
    - consul
    - elasticsearch

elasticsearch:
 container_name: elasticsearch
 image: elasticsearch:latest
 hostname: "elasticsearch"
 ports:
   - "9200:9200"
   - "9300:9300"
 environment:
   ES_HEAP_SIZE: 512m
   ES_CLUSTER_NAME: Kazoup
# Flag service
flag-api:
  command: --registry_address=registry:8500
  image: kazoup/flag-api:latest
  links:
    - consul:registry

flag-srv:
  command: --registry_address=registry:8500
  image: kazoup/flag-srv:latest
  links:
    - consul:registry

smtp-api:
  command: --registry_address=registry:8500
  image: kazoup/smtp-api
  links:
    - consul

smtp-srv:
  command: --registry_address=registry:8500 --email_host=SERVER_ADDRESS --email_host_port=SMPT_SERVER_PORT --email_host_user=USERNAME --email_host_password=PASSWORD --default_from_email=noreply@company.com
  image: kazoup/smtp-srv
  links:
    - consul

