version: '2'
services:
  audio-srv:
    command: go run src/github.com/kazoup/platform/audio/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  auth-web:
    command: go run src/github.com/kazoup/platform/auth/web/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  config-web:
    command: go run src/github.com/kazoup/platform/config/web/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  crawler-srv:
    command: go run src/github.com/kazoup/platform/crawler/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  datasource-srv:
    command: go run src/github.com/kazoup/platform/datasource/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  document-srv:
    command: go run src/github.com/kazoup/platform/document/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - tika
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
      - TIKA_URL=http://tika:9998
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  file-srv:
    command: bash -c "cd /go/src/github.com/kazoup/platform/file/srv && go build . && ./srv --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp"
    image: golang:wheezy
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  user-srv:
    command: go run src/github.com/kazoup/platform/user/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  channel-srv:
    command: go run src/github.com/kazoup/platform/channel/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  image-srv:
    command: go run src/github.com/kazoup/platform/image/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  media-web:
    command: go run src/github.com/kazoup/platform/media/web/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  monitor-srv:
    command: go run src/github.com/kazoup/platform/monitor/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  monitor-web:
    command: bash -c "cd /go/src/github.com/kazoup/platform/monitor/web && go build . && ./web --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp"
    image: golang:wheezy
    external_links:
    - registry
    - nats
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  notification-srv:
    command: go run src/github.com/kazoup/platform/notification/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  notification-web:
    command: go run src/github.com/kazoup/platform/notification/web/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  profile-srv:
    command: go run src/github.com/kazoup/platform/profile/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  quota-srv:
    command: go run src/github.com/kazoup/platform/quota/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  sentiment-srv:
    command: go run src/github.com/kazoup/platform/sentiment/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  entities-srv:
    command: go run src/github.com/kazoup/platform/entities/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  thumbnail-srv:
    command: go run src/github.com/kazoup/platform/thumbnail/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

  translate-srv:
    command: go run src/github.com/kazoup/platform/translate/srv/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --server_address=0.0.0.0:9090 --transport=tcp
    image: golang:1.7-alpine3.5
    external_links:
    - registry
    - nats
    - redis
    expose:
      - "9090"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/srv/google-app-credentials/google-cloud-service-account.json
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - REDIS_URL=redis:6379
    volumes:
      - "./cmd/kazoup/ssl:/ssl"
      - "../../../:/go/src/"
      - "./cmd/kazoup/google-app-credentials:/srv/google-app-credentials"

networks:
  default:
    external:
      name: kazoup-platform
