# 1. Create Docker network 'docker network create kazoup-platform'
# 2. Run elasticsearch
# 3. Run scripts/es_init.sh
version: '2'
services:
  elasticsearch:
   image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
   hostname: "elasticsearch"
   networks:
     - kazoup-platform
   ports:
     - "9200:9200"
     - "9300:9300"
   environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=\"*\""
      - "http.cors.allow-headers=Authorization"
      - "xpack.security.enabled=false"
   ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
   mem_limit: 2g
   cap_add:
   - IPC_LOCK

  kibana:
    image: docker.elastic.co/kibana/kibana:5.2.0
    hostname: "kibana"
    networks:
      - kazoup-platform
    links:
      - elasticsearch
    ports:
      - 5601:5601

  redis:
    image: redis:3.2
    hostname: "redis"
    networks:
      - kazoup-platform
    ports:
      - "6379:6379"

  tika:
   image: logicalspark/docker-tikaserver
   hostname: "tika"
   networks:
     - kazoup-platform
   ports:
     - "9998:9998"

  nats:
    image: nats:0.9.6
    networks:
      - kazoup-platform
    entrypoint: "/gnatsd"
    expose:
      - "4222"
    ports:
      - "8222:8222"

  registry:
    command: -server -bootstrap -rejoin -log-level err
    image: progrium/consul:latest
    networks:
      - kazoup-platform
    ports:
    - "8300:8300"
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"

  web:
    command: go run src/github.com/kazoup/platform/micro/web/main.go --registry_address=registry:8500 --broker=nats --broker_address=nats:4222 --register_interval=5 --register_ttl=10 --web_namespace=com.kazoup.web  --enable_stats=true  --selector=cache --enable_tls -tls_cert_file=/ssl/all.pem --tls_key_file=/ssl/key.pem --web_cors=* --transport=tcp web
    image: golang:1.7-alpine3.5
    networks:
      - kazoup-platform
    links:
    - registry
    - nats
    ports:
    - "8082:8082"
    volumes:
    - "./cmd/kazoup/ssl:/ssl"
    - "../../../:/go/src/"

networks:
  kazoup-platform:
    external: true
