apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: media-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: media-web
    spec:
      containers:
      - name: media-web
        command: [
                  "/web",
                  "--registry=kubernetes",    
                  "--server_address=0.0.0.0:9090",
                  "--register_ttl=60",
                  "--register_interval=30",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--selector=cache",
                  ]
        image: eu.gcr.io/desktop-1470249894548/media-web:latest
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value:  "/google-cloud-service-account/google-cloud-service-account.json"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: media-port
        volumeMounts: 
        - name: google-cloud-service-account
          mountPath: "/google-cloud-service-account"
          readOnly: true
      volumes:
      - name: google-cloud-service-account
        secret: 
          secretName: "google-cloud-service-account"