apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: notification-web
spec:
  replicas: 1
  selector:
    name: notification-web
  template:
    metadata:
      labels:
        name: notification-web
    spec:
      containers:
        - name: notification
          resources:
            limits:
              cpu: "10m"
          command: [
                "/web",
                "--registry_address=$(REGISTRY_SERVICE_HOST)",
                "--server_address=0.0.0.0:9090",
                "--register_ttl=60",
                "--register_interval=30",
                "--broker=nats",
                "--broker_address=nats:4222",
                "--selector=cache",
                "--transport=tcp",
          ]
          image: kazoup/notification-web:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 9090
            name: notif-port
