apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: notification-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: notification-web
    spec:
      containers:
      - name: notification-web
        command: [
                  "/web",
                  "--registry_address=$(REGISTRY_SERVICE_HOST)",
                  "--server_address=0.0.0.0:9090",
                  "--register_ttl=60",
                  "--register_interval=30",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--selector=cache",
                  "--transport=tcp",
                  ]
        image: eu.gcr.io/desktop-1470249894548/notification-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: notif-port
