apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui-web
spec:
  replicas: 3
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: ui-web
        app: ui-web
        test: test
    spec:
      containers:
      - name: ui-web
        command: [
                  "/web"
                  ]
        image: eu.gcr.io/desktop-1470249894548/ui-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: ui-port
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        - name: google-cloud-service-account
          mountPath: "/google-cloud-service-account"
          readOnly: true
        - name: aws-credentials
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: "ssl"
      - name: google-cloud-service-account
        secret: 
          secretName: "google-cloud-service-account"
      - name: aws-credentials
        secret: 
          secretName: "aws-credentials"
