// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/lib/db/custom/proto/custom/custom.proto
// DO NOT EDIT!

/*
Package proto_custom is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/lib/db/custom/proto/custom/custom.proto

It has these top-level messages:
	ScrollUnprocessedFilesRequest
	ScrollUnprocessedFilesResponse
	ScrollDatasourcesRequest
	ScrollDatasourcesResponse
*/
package proto_custom

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ScrollUnprocessedFilesRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Category string `protobuf:"bytes,2,opt,name=category" json:"category,omitempty"`
	Field    string `protobuf:"bytes,3,opt,name=field" json:"field,omitempty"`
}

func (m *ScrollUnprocessedFilesRequest) Reset()                    { *m = ScrollUnprocessedFilesRequest{} }
func (m *ScrollUnprocessedFilesRequest) String() string            { return proto.CompactTextString(m) }
func (*ScrollUnprocessedFilesRequest) ProtoMessage()               {}
func (*ScrollUnprocessedFilesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ScrollUnprocessedFilesRequest) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *ScrollUnprocessedFilesRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ScrollUnprocessedFilesRequest) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

type ScrollUnprocessedFilesResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ScrollUnprocessedFilesResponse) Reset()                    { *m = ScrollUnprocessedFilesResponse{} }
func (m *ScrollUnprocessedFilesResponse) String() string            { return proto.CompactTextString(m) }
func (*ScrollUnprocessedFilesResponse) ProtoMessage()               {}
func (*ScrollUnprocessedFilesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ScrollUnprocessedFilesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type ScrollDatasourcesRequest struct {
}

func (m *ScrollDatasourcesRequest) Reset()                    { *m = ScrollDatasourcesRequest{} }
func (m *ScrollDatasourcesRequest) String() string            { return proto.CompactTextString(m) }
func (*ScrollDatasourcesRequest) ProtoMessage()               {}
func (*ScrollDatasourcesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ScrollDatasourcesResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ScrollDatasourcesResponse) Reset()                    { *m = ScrollDatasourcesResponse{} }
func (m *ScrollDatasourcesResponse) String() string            { return proto.CompactTextString(m) }
func (*ScrollDatasourcesResponse) ProtoMessage()               {}
func (*ScrollDatasourcesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ScrollDatasourcesResponse) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*ScrollUnprocessedFilesRequest)(nil), "proto.custom.ScrollUnprocessedFilesRequest")
	proto.RegisterType((*ScrollUnprocessedFilesResponse)(nil), "proto.custom.ScrollUnprocessedFilesResponse")
	proto.RegisterType((*ScrollDatasourcesRequest)(nil), "proto.custom.ScrollDatasourcesRequest")
	proto.RegisterType((*ScrollDatasourcesResponse)(nil), "proto.custom.ScrollDatasourcesResponse")
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/lib/db/custom/proto/custom/custom.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0x04, 0x31,
	0x10, 0x84, 0x59, 0xc5, 0x45, 0x1b, 0x4f, 0x83, 0xc8, 0xb8, 0xa0, 0x48, 0x4e, 0x9e, 0x26, 0x87,
	0xbd, 0x78, 0x16, 0xf1, 0x01, 0x56, 0x7c, 0x80, 0xfc, 0xf4, 0x8e, 0xc1, 0xcc, 0x74, 0x4c, 0x77,
	0x40, 0x7d, 0x7a, 0x31, 0x59, 0xf7, 0xa4, 0x7b, 0x2a, 0xbe, 0x2a, 0x2a, 0x15, 0x1a, 0x1e, 0xc6,
	0x20, 0xaf, 0xc5, 0x0e, 0x8e, 0x26, 0xfd, 0x66, 0xbe, 0xa8, 0x24, 0x9d, 0xa2, 0x91, 0x2d, 0xe5,
	0x49, 0xc7, 0x60, 0xb5, 0xb7, 0xda, 0x15, 0x16, 0x9a, 0x74, 0xca, 0x24, 0xf4, 0x0b, 0x4d, 0x86,
	0xea, 0x75, 0xe7, 0x55, 0x86, 0xe6, 0xa9, 0x11, 0xae, 0x9f, 0x5d, 0xa6, 0x18, 0x5f, 0xe6, 0x94,
	0xc9, 0x21, 0x33, 0xfa, 0xa7, 0x10, 0x91, 0x37, 0xf8, 0x5e, 0x90, 0xa5, 0xbb, 0x80, 0x93, 0x30,
	0x7b, 0xfc, 0xe8, 0x17, 0xb7, 0x8b, 0xbb, 0xb3, 0x4d, 0x83, 0x6e, 0x05, 0xa7, 0xce, 0x08, 0x8e,
	0x94, 0x3f, 0xfb, 0xa3, 0x1a, 0xec, 0xf9, 0xa7, 0xb1, 0x0d, 0x18, 0x7d, 0x7f, 0xdc, 0x1a, 0x15,
	0xd4, 0x3d, 0xdc, 0xfc, 0x37, 0xc4, 0x89, 0x66, 0xc6, 0xee, 0x12, 0x96, 0x19, 0xb9, 0x44, 0xd9,
	0x4d, 0xed, 0x48, 0xad, 0xa0, 0x6f, 0xcd, 0x47, 0x23, 0x86, 0xa9, 0x64, 0xb7, 0xff, 0x9d, 0x5a,
	0xc3, 0xd5, 0x1f, 0xd9, 0xe1, 0x07, 0xed, 0xb2, 0x5e, 0x60, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xe2, 0x74, 0x92, 0xda, 0x4e, 0x01, 0x00, 0x00,
}
