// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/notification/srv/proto/notification/notification.proto
// DO NOT EDIT!

/*
Package go_micro_srv_notification is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/notification/srv/proto/notification/notification.proto

It has these top-level messages:
	NotificationMessage
	DatasourceAddedMessage
*/
package go_micro_srv_notification

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationMessage struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *NotificationMessage) Reset()                    { *m = NotificationMessage{} }
func (m *NotificationMessage) String() string            { return proto.CompactTextString(m) }
func (*NotificationMessage) ProtoMessage()               {}
func (*NotificationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DatasourceAddedMessage struct {
}

func (m *DatasourceAddedMessage) Reset()                    { *m = DatasourceAddedMessage{} }
func (m *DatasourceAddedMessage) String() string            { return proto.CompactTextString(m) }
func (*DatasourceAddedMessage) ProtoMessage()               {}
func (*DatasourceAddedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*NotificationMessage)(nil), "go.micro.srv.notification.NotificationMessage")
	proto.RegisterType((*DatasourceAddedMessage)(nil), "go.micro.srv.notification.DatasourceAddedMessage")
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/notification/srv/proto/notification/notification.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 155 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x0a, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xac, 0xca, 0x2f, 0x2d, 0xd0, 0x2f, 0xc8,
	0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0xcf, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x4e, 0x2c,
	0xc9, 0xcc, 0xcf, 0xd3, 0x2f, 0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x47, 0x15, 0x46,
	0xe6, 0xe8, 0x81, 0xe5, 0x85, 0x24, 0xd3, 0xf3, 0xf5, 0x72, 0x33, 0x93, 0x8b, 0xf2, 0xf5, 0x80,
	0x7a, 0xf4, 0x90, 0x15, 0x28, 0x69, 0x72, 0x09, 0xfb, 0x21, 0xf1, 0x7d, 0x53, 0x8b, 0x8b, 0x13,
	0xd3, 0x53, 0x85, 0x84, 0xb8, 0x58, 0x32, 0xf3, 0xd2, 0xf2, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x25, 0x09, 0x2e, 0x31, 0x97, 0xc4, 0x92, 0xc4, 0xe2, 0xfc, 0xd2, 0xa2, 0xe4,
	0x54, 0xc7, 0x94, 0x94, 0xd4, 0x14, 0xa8, 0xea, 0x24, 0x36, 0xb0, 0x35, 0xc6, 0x80, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x96, 0xe2, 0x8f, 0x27, 0xbb, 0x00, 0x00, 0x00,
}
