// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/notification/srv/proto/notification/notification.proto
// DO NOT EDIT!

/*
Package go_micro_srv_notification is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/notification/srv/proto/notification/notification.proto

It has these top-level messages:
	NotificationMessage
*/
package go_micro_srv_notification

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NotificationMessage struct {
	Info   string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
	Code   string `protobuf:"bytes,2,opt,name=code" json:"code,omitempty"`
	Data   string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *NotificationMessage) Reset()                    { *m = NotificationMessage{} }
func (m *NotificationMessage) String() string            { return proto.CompactTextString(m) }
func (*NotificationMessage) ProtoMessage()               {}
func (*NotificationMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func init() {
	proto.RegisterType((*NotificationMessage)(nil), "go.micro.srv.notification.NotificationMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Notification service

type NotificationClient interface {
}

type notificationClient struct {
	c           client.Client
	serviceName string
}

func NewNotificationClient(serviceName string, c client.Client) NotificationClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.notification"
	}
	return &notificationClient{
		c:           c,
		serviceName: serviceName,
	}
}

// Server API for Notification service

type NotificationHandler interface {
}

func RegisterNotificationHandler(s server.Server, hdlr NotificationHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Notification{hdlr}, opts...))
}

type Notification struct {
	NotificationHandler
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/notification/srv/proto/notification/notification.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 181 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x54, 0xce, 0x3f, 0xcf, 0xc2, 0x20,
	0x10, 0x06, 0xf0, 0xf4, 0x7d, 0x9b, 0x1a, 0x89, 0x71, 0xc0, 0x41, 0xdc, 0x8c, 0x93, 0x13, 0x24,
	0xfa, 0x29, 0x1c, 0x34, 0xd1, 0x2f, 0x60, 0x28, 0xd0, 0x7a, 0x6a, 0x7b, 0x0d, 0x7f, 0x1c, 0xfc,
	0xf4, 0x0a, 0x5d, 0x70, 0x7b, 0x9e, 0x1f, 0x5c, 0xee, 0xc8, 0xb9, 0x05, 0x7f, 0x0b, 0x35, 0x57,
	0xd8, 0x89, 0x87, 0x7c, 0x63, 0x18, 0xc4, 0xf0, 0x94, 0xbe, 0x41, 0xdb, 0x89, 0x1e, 0x3d, 0x34,
	0xa0, 0xa4, 0x07, 0xec, 0x85, 0xb3, 0x2f, 0x31, 0x58, 0xf4, 0xf8, 0xcb, 0x79, 0xe1, 0xe9, 0x9d,
	0xae, 0x5a, 0xe4, 0x1d, 0x28, 0x8b, 0xfc, 0x3b, 0xc3, 0xf3, 0x0f, 0x9b, 0x3b, 0x59, 0x9c, 0xb2,
	0x7e, 0x34, 0xce, 0xc9, 0xd6, 0x50, 0x4a, 0x4a, 0xe8, 0x1b, 0x64, 0xc5, 0xba, 0xd8, 0x4e, 0x2f,
	0x29, 0x47, 0x53, 0xa8, 0x0d, 0xfb, 0x1b, 0x2d, 0xe6, 0x68, 0x5a, 0x7a, 0xc9, 0xfe, 0x47, 0x8b,
	0x99, 0x2e, 0xc9, 0x24, 0x38, 0x63, 0xaf, 0xa0, 0x59, 0x99, 0xb8, 0x8a, 0xf5, 0xa0, 0x77, 0x73,
	0x32, 0xcb, 0x77, 0xd5, 0x55, 0xba, 0x6e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xbf, 0xc7, 0xa6,
	0xeb, 0xf2, 0x00, 0x00, 0x00,
}
