apiVersion: v1
kind: ReplicationController
metadata:
  namespace: default
  name: registry
spec:
  replicas: 2
  selector:
    name: registry
  template:
    metadata:
      labels:
        app: registry
        name: registry
    spec:
      containers:
        - name: registry
          command: [ "/bin/start", "-server", "-bootstrap-expect", "3", "-join", $(REGISTRY_SERVICE_HOST) ]
          image: consul:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 443
            name: https-port
          - containerPort: 8080
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server
