version: "2"
services:
        # Micro
        registry:
          command: -server -bootstrap -rejoin -log-level err
          image: progrium/consul:latest
          ports:
          - "8300:8300"
          - "8400:8400"
          - "8500:8500"
          - "8600:53/udp"

        api:
          command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 --api_cors=* --enable_stats api
          image: microhq/micro
          links:
          - registry
          ports:
          - "8080:8080"

        web:
          command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
          image: microhq/micro
          links:
          - registry
          ports:
          - "8082:8082"

        # Elastic service
        elastic-api:
          command: --registry_address=registry:8500
          image : kazoup/elastic-api
          links:
          - registry

        elastic-srv:
          command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
          image: kazoup/elastic-srv
          links:
          - elasticsearch
          - registry

        elasticsearch:
         image: elasticsearch:latest
         hostname: "elasticsearch"
         ports:
           - "9200:9200"
           - "9300:9300"
         environment:
           ES_HEAP_SIZE: 512m
           ES_CLUSTER_NAME: Kazoup
        # Flag service
        flag-api:
          command: --registry_address=registry:8500
          image: kazoup/flag-api:latest
          links:
          - registry

        flag-srv:
          command: --registry_address=registry:8500
          image: kazoup/flag-srv:latest
          links:
          - elasticsearch
          - registry

        smtp-api:
          command: --registry_address=registry:8500
          image: kazoup/smtp-api
          links:
          - registry

        smtp-srv:
          command: --registry_address=registry:8500 --email_host=SERVER_ADDRESS --email_host_port=SMPT_SERVER_PORT --email_host_user=USERNAME --email_host_password=PASSWORD --default_from_email=noreply@company.com
          image: kazoup/smtp-srv
          links:
          - registry

        auth-api:
          command: --registry_address=registry:8500
          image: kazoup/auth-api
          links:
          - registry

        proxy-srv:
          command: --registry_address=registry:8500
          image: kazoup/proxy-srv
          links:
          - registry
          ports:
          - "8000:8000"

        dashboard-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/dashboard-web
           links:
           - registry

        login-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/login-web
           links:
           - registry

        analytics-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/analytics-web
           links:
           - registry

        search-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/search-web
           links: 
           - registry

        web-docs:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/docs-web
           links:
           - registry

        logs-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/logs-web
           links:
           - registry

        settings-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/settings-web
           links:
           - registry

        static-web:
           command: --registry_address=registry:8500 --environment=prod
           image: kazoup/static-web
           links: 
           - registry

        ldap-srv:
           command: --registry_address=registry:8500
           image: kazoup/ldap-srv
           links:
           - registry

        crawler-srv:
           command: --registry_address=registry:8500
           image: kazoup/crawler-srv
           links: 
           - registry


        publish-srv:
           command: --registry_address=registry:8500
           image: kazoup/publish-srv
           links: 
           - registry

        indexer-srv:
           command: --registry_address=registry:8500
           image: kazoup/indexer-srv
           links: 
           - registry
