version: "2"
services:
        # Flag service
        flag-api:
          command: --registry_address=registry:8500
          image: kazoup/flag-api:latest
          links:
          - registry

        flag-srv:
          command: --registry_address=registry:8500
          image: kazoup/flag-srv:latest
          links:
          - elasticsearch
          - registry

