// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto
// DO NOT EDIT!

/*
Package crawler is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto

It has these top-level messages:
	FileMessage
	SlackUserMessage
	SlackChannelMessage
*/
package crawler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FileMessage struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Index  string `protobuf:"bytes,3,opt,name=index" json:"index,omitempty"`
	Notify bool   `protobuf:"varint,4,opt,name=notify" json:"notify,omitempty"`
	Data   string `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *FileMessage) Reset()                    { *m = FileMessage{} }
func (m *FileMessage) String() string            { return proto.CompactTextString(m) }
func (*FileMessage) ProtoMessage()               {}
func (*FileMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SlackUserMessage struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *SlackUserMessage) Reset()                    { *m = SlackUserMessage{} }
func (m *SlackUserMessage) String() string            { return proto.CompactTextString(m) }
func (*SlackUserMessage) ProtoMessage()               {}
func (*SlackUserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SlackChannelMessage struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *SlackChannelMessage) Reset()                    { *m = SlackChannelMessage{} }
func (m *SlackChannelMessage) String() string            { return proto.CompactTextString(m) }
func (*SlackChannelMessage) ProtoMessage()               {}
func (*SlackChannelMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto.RegisterType((*FileMessage)(nil), "FileMessage")
	proto.RegisterType((*SlackUserMessage)(nil), "SlackUserMessage")
	proto.RegisterType((*SlackChannelMessage)(nil), "SlackChannelMessage")
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x72, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xac, 0xca, 0x2f, 0x2d, 0xd0, 0x2f, 0xc8,
	0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x4f, 0x2e, 0x4a, 0x2c, 0xcf, 0x49, 0x2d, 0xd2, 0x2f,
	0x2e, 0x2a, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x8b, 0x40, 0x69, 0x3d, 0xb0, 0xa8, 0x52,
	0x05, 0x17, 0xb7, 0x5b, 0x66, 0x4e, 0xaa, 0x6f, 0x6a, 0x71, 0x71, 0x62, 0x7a, 0xaa, 0x10, 0x1f,
	0x17, 0x53, 0x66, 0x8a, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x90, 0x25, 0x24, 0xce, 0xc5,
	0x5e, 0x5a, 0x9c, 0x5a, 0x14, 0x0f, 0x14, 0x64, 0x02, 0x0b, 0xb2, 0x81, 0xb8, 0x9e, 0x29, 0x42,
	0x22, 0x5c, 0xac, 0x99, 0x79, 0x29, 0xa9, 0x15, 0x12, 0xcc, 0x60, 0x61, 0x08, 0x47, 0x48, 0x8c,
	0x8b, 0x2d, 0x2f, 0xbf, 0x24, 0x33, 0xad, 0x52, 0x82, 0x05, 0x28, 0xcc, 0x11, 0x04, 0xe5, 0x09,
	0x09, 0x71, 0xb1, 0xa4, 0x24, 0x96, 0x24, 0x4a, 0xb0, 0x82, 0x15, 0x83, 0xd9, 0x4a, 0x3e, 0x5c,
	0x02, 0xc1, 0x39, 0x89, 0xc9, 0xd9, 0xa1, 0x40, 0x03, 0x71, 0x59, 0x0f, 0xb7, 0x85, 0x09, 0xd9,
	0x16, 0x98, 0x69, 0xcc, 0x48, 0xa6, 0xf9, 0x73, 0x09, 0x83, 0x4d, 0x73, 0xce, 0x48, 0xcc, 0xcb,
	0x4b, 0xcd, 0xa1, 0xd8, 0xc0, 0x24, 0x36, 0x70, 0xf8, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x04, 0xfd, 0x4b, 0xe5, 0x65, 0x01, 0x00, 0x00,
}
