// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto
// DO NOT EDIT!

/*
Package crawler is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto

It has these top-level messages:
	Status
	StartRequest
	StartResponse
	StopRequest
	StopResponse
	SearchRequest
	SearchResponse
	StatusRequest
	StatusResponse
	Metric
	FileMessage
	SlackUserMessage
	SlackChannelMessage
	CrawlerFinishedMessage
*/
package crawler

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status struct {
	Id          int64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Type        string            `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Description string            `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Running     bool              `protobuf:"varint,4,opt,name=running" json:"running,omitempty"`
	Config      map[string]string `protobuf:"bytes,5,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Status) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type StartRequest struct {
	Url    string            `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Config map[string]string `protobuf:"bytes,2,rep,name=config" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *StartRequest) Reset()                    { *m = StartRequest{} }
func (m *StartRequest) String() string            { return proto.CompactTextString(m) }
func (*StartRequest) ProtoMessage()               {}
func (*StartRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *StartRequest) GetConfig() map[string]string {
	if m != nil {
		return m.Config
	}
	return nil
}

type StartResponse struct {
}

func (m *StartResponse) Reset()                    { *m = StartResponse{} }
func (m *StartResponse) String() string            { return proto.CompactTextString(m) }
func (*StartResponse) ProtoMessage()               {}
func (*StartResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type StopRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *StopRequest) Reset()                    { *m = StopRequest{} }
func (m *StopRequest) String() string            { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()               {}
func (*StopRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type StopResponse struct {
}

func (m *StopResponse) Reset()                    { *m = StopResponse{} }
func (m *StopResponse) String() string            { return proto.CompactTextString(m) }
func (*StopResponse) ProtoMessage()               {}
func (*StopResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SearchRequest struct {
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchResponse struct {
	Crawls map[string]*Status `protobuf:"bytes,1,rep,name=crawls" json:"crawls,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchResponse) GetCrawls() map[string]*Status {
	if m != nil {
		return m.Crawls
	}
	return nil
}

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type StatusResponse struct {
	Counter int64 `protobuf:"varint,1,opt,name=counter" json:"counter,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Metric struct {
	Count int64 `protobuf:"varint,1,opt,name=count" json:"count,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type FileMessage struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *FileMessage) Reset()                    { *m = FileMessage{} }
func (m *FileMessage) String() string            { return proto.CompactTextString(m) }
func (*FileMessage) ProtoMessage()               {}
func (*FileMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SlackUserMessage struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *SlackUserMessage) Reset()                    { *m = SlackUserMessage{} }
func (m *SlackUserMessage) String() string            { return proto.CompactTextString(m) }
func (*SlackUserMessage) ProtoMessage()               {}
func (*SlackUserMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type SlackChannelMessage struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Data  string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *SlackChannelMessage) Reset()                    { *m = SlackChannelMessage{} }
func (m *SlackChannelMessage) String() string            { return proto.CompactTextString(m) }
func (*SlackChannelMessage) ProtoMessage()               {}
func (*SlackChannelMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type CrawlerFinishedMessage struct {
	DatasourceId string `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId" json:"datasource_id,omitempty"`
}

func (m *CrawlerFinishedMessage) Reset()                    { *m = CrawlerFinishedMessage{} }
func (m *CrawlerFinishedMessage) String() string            { return proto.CompactTextString(m) }
func (*CrawlerFinishedMessage) ProtoMessage()               {}
func (*CrawlerFinishedMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func init() {
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*StartRequest)(nil), "StartRequest")
	proto.RegisterType((*StartResponse)(nil), "StartResponse")
	proto.RegisterType((*StopRequest)(nil), "StopRequest")
	proto.RegisterType((*StopResponse)(nil), "StopResponse")
	proto.RegisterType((*SearchRequest)(nil), "SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "SearchResponse")
	proto.RegisterType((*StatusRequest)(nil), "StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*Metric)(nil), "Metric")
	proto.RegisterType((*FileMessage)(nil), "FileMessage")
	proto.RegisterType((*SlackUserMessage)(nil), "SlackUserMessage")
	proto.RegisterType((*SlackChannelMessage)(nil), "SlackChannelMessage")
	proto.RegisterType((*CrawlerFinishedMessage)(nil), "CrawlerFinishedMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Crawl service

type CrawlClient interface {
	Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error)
	Stop(ctx context.Context, in *StopRequest, opts ...client.CallOption) (*StopResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (Crawl_StatusClient, error)
}

type crawlClient struct {
	c           client.Client
	serviceName string
}

func NewCrawlClient(serviceName string, c client.Client) CrawlClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "crawl"
	}
	return &crawlClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *crawlClient) Start(ctx context.Context, in *StartRequest, opts ...client.CallOption) (*StartResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Crawl.Start", in)
	out := new(StartResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlClient) Stop(ctx context.Context, in *StopRequest, opts ...client.CallOption) (*StopResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Crawl.Stop", in)
	out := new(StopResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Crawl.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlClient) Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (Crawl_StatusClient, error) {
	req := c.c.NewRequest(c.serviceName, "Crawl.Status", &StatusRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &crawlStatusClient{stream}, nil
}

type Crawl_StatusClient interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StatusResponse, error)
}

type crawlStatusClient struct {
	stream client.Streamer
}

func (x *crawlStatusClient) Close() error {
	return x.stream.Close()
}

func (x *crawlStatusClient) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *crawlStatusClient) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *crawlStatusClient) Recv() (*StatusResponse, error) {
	m := new(StatusResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Crawl service

type CrawlHandler interface {
	Start(context.Context, *StartRequest, *StartResponse) error
	Stop(context.Context, *StopRequest, *StopResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Status(context.Context, *StatusRequest, Crawl_StatusStream) error
}

func RegisterCrawlHandler(s server.Server, hdlr CrawlHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Crawl{hdlr}, opts...))
}

type Crawl struct {
	CrawlHandler
}

func (h *Crawl) Start(ctx context.Context, in *StartRequest, out *StartResponse) error {
	return h.CrawlHandler.Start(ctx, in, out)
}

func (h *Crawl) Stop(ctx context.Context, in *StopRequest, out *StopResponse) error {
	return h.CrawlHandler.Stop(ctx, in, out)
}

func (h *Crawl) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.CrawlHandler.Search(ctx, in, out)
}

func (h *Crawl) Status(ctx context.Context, stream server.Streamer) error {
	m := new(StatusRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.CrawlHandler.Status(ctx, m, &crawlStatusStream{stream})
}

type Crawl_StatusStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StatusResponse) error
}

type crawlStatusStream struct {
	stream server.Streamer
}

func (x *crawlStatusStream) Close() error {
	return x.stream.Close()
}

func (x *crawlStatusStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *crawlStatusStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *crawlStatusStream) Send(m *StatusResponse) error {
	return x.stream.Send(m)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/crawler/srv/proto/crawler/crawler.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 550 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xd1, 0x6e, 0xd3, 0x30,
	0x14, 0x5d, 0xda, 0xb5, 0x63, 0x37, 0x6d, 0x37, 0x79, 0x08, 0x85, 0xa2, 0xa1, 0x2a, 0x08, 0xa9,
	0x02, 0xe1, 0x42, 0xf7, 0x02, 0x48, 0xbc, 0xac, 0x62, 0x08, 0x89, 0x09, 0x29, 0x15, 0xcf, 0x28,
	0x4b, 0xbc, 0xd6, 0x6a, 0x66, 0x07, 0xdb, 0x19, 0x94, 0x3f, 0xe0, 0x85, 0xaf, 0xe1, 0x43, 0xf8,
	0x24, 0x6c, 0xc7, 0x69, 0x93, 0xc1, 0xdb, 0x78, 0xea, 0xbd, 0xc7, 0xf7, 0x9e, 0x9e, 0xe3, 0x9c,
	0x04, 0x4e, 0x17, 0x54, 0x2d, 0x8b, 0x0b, 0x9c, 0xf0, 0xab, 0xc9, 0x2a, 0xfe, 0xce, 0x8b, 0x7c,
	0x92, 0x67, 0xb1, 0xba, 0xe4, 0xe2, 0x6a, 0x92, 0x88, 0xf8, 0x6b, 0x46, 0xc4, 0x44, 0x8a, 0xeb,
	0x49, 0x2e, 0xb8, 0xe2, 0x1b, 0xc4, 0xfd, 0x62, 0x8b, 0x86, 0xbf, 0x3d, 0xe8, 0xce, 0x55, 0xac,
	0x0a, 0x89, 0x06, 0xd0, 0xa2, 0x69, 0xe0, 0x8d, 0xbc, 0x71, 0x3b, 0xd2, 0x15, 0x42, 0xb0, 0xab,
	0xd6, 0x39, 0x09, 0x5a, 0x1a, 0xd9, 0x8f, 0x6c, 0x8d, 0x46, 0xe0, 0xa7, 0x44, 0x26, 0x82, 0xe6,
	0x8a, 0x72, 0x16, 0xb4, 0xed, 0x51, 0x1d, 0x42, 0x01, 0xec, 0x89, 0x82, 0x31, 0xca, 0x16, 0xc1,
	0xae, 0x3e, 0xbd, 0x13, 0x55, 0x2d, 0x7a, 0x0a, 0xdd, 0x84, 0xb3, 0x4b, 0xba, 0x08, 0x3a, 0xa3,
	0xf6, 0xd8, 0x9f, 0x1e, 0xe1, 0xf2, 0x8f, 0xf1, 0xcc, 0xa2, 0x6f, 0x99, 0x12, 0xeb, 0xc8, 0x8d,
	0x0c, 0x5f, 0x81, 0x5f, 0x83, 0xd1, 0x21, 0xb4, 0x57, 0x64, 0x6d, 0xc5, 0xed, 0x47, 0xa6, 0x44,
	0x77, 0xa1, 0x73, 0x1d, 0x67, 0x45, 0x25, 0xaf, 0x6c, 0x5e, 0xb7, 0x5e, 0x7a, 0xe1, 0x4f, 0x0f,
	0x7a, 0x9a, 0x59, 0xa8, 0x88, 0x7c, 0x29, 0x88, 0x54, 0x66, 0xb9, 0x10, 0x59, 0xb5, 0xac, 0x4b,
	0xf4, 0x62, 0x23, 0xa5, 0x65, 0xa5, 0xdc, 0xc7, 0xf5, 0x85, 0xff, 0x2d, 0xe8, 0x00, 0xfa, 0x8e,
	0x5e, 0xe6, 0x9c, 0x49, 0x12, 0x1e, 0x83, 0x3f, 0x57, 0x3c, 0xaf, 0xf4, 0xdd, 0xb8, 0xf8, 0x70,
	0x60, 0xf4, 0x9b, 0x63, 0x37, 0x6e, 0xf6, 0x49, 0x2c, 0x92, 0xa5, 0x5b, 0x08, 0x7f, 0x78, 0x30,
	0xa8, 0x90, 0x72, 0x06, 0x9d, 0x68, 0x47, 0xe6, 0xc1, 0x4a, 0xcd, 0x63, 0x1c, 0x3d, 0xc0, 0xcd,
	0x01, 0x3c, 0xb3, 0xa7, 0x95, 0x27, 0xdb, 0x0c, 0x4f, 0xb5, 0xa7, 0x2d, 0xfc, 0x0f, 0x4f, 0xc7,
	0x75, 0x4f, 0xfe, 0x74, 0xcf, 0x3d, 0xb1, 0xbf, 0xcd, 0x19, 0xd0, 0x89, 0x7b, 0xa2, 0xb5, 0x39,
	0xc0, 0x69, 0xd3, 0x91, 0x48, 0x78, 0xc1, 0x14, 0x11, 0xce, 0x64, 0xd5, 0x86, 0x0f, 0xa1, 0x7b,
	0x4e, 0x94, 0xa0, 0x89, 0xb9, 0x3d, 0x0b, 0xba, 0x89, 0xb2, 0x09, 0xdf, 0x81, 0x7f, 0x46, 0x33,
	0x72, 0x4e, 0xa4, 0x8c, 0x17, 0xa4, 0x76, 0x51, 0xfb, 0x36, 0xa1, 0x7a, 0x89, 0xb2, 0x94, 0x7c,
	0xab, 0xae, 0xdc, 0x36, 0x26, 0xb7, 0x69, 0xac, 0x62, 0x17, 0x4e, 0x5b, 0x87, 0x1f, 0xe0, 0x70,
	0x9e, 0xc5, 0xc9, 0xea, 0x93, 0x24, 0xe2, 0xf6, 0x6c, 0x1f, 0xe1, 0xc8, 0xb2, 0xcd, 0x96, 0x31,
	0x63, 0x24, 0xbb, 0x3d, 0xe1, 0x1b, 0xb8, 0x37, 0x2b, 0x5f, 0xcb, 0x33, 0xca, 0xa8, 0x5c, 0x92,
	0xb4, 0xe2, 0x7c, 0x04, 0x7d, 0x33, 0x21, 0x79, 0x21, 0x12, 0xf2, 0x79, 0x43, 0xdf, 0xdb, 0x82,
	0xef, 0xd3, 0xe9, 0x2f, 0x0f, 0x3a, 0x76, 0x1f, 0x8d, 0xa1, 0x63, 0xa3, 0x86, 0xfa, 0x8d, 0x44,
	0x0f, 0x07, 0xb8, 0x99, 0xc0, 0x1d, 0xf4, 0x18, 0x76, 0x4d, 0xc8, 0x50, 0x0f, 0xd7, 0xa2, 0x38,
	0xec, 0xe3, 0x46, 0xf2, 0x76, 0xcc, 0x4b, 0x5b, 0x06, 0x09, 0x0d, 0x70, 0x23, 0x84, 0xc3, 0x83,
	0x1b, 0x09, 0xd3, 0xc3, 0xcf, 0xb6, 0xdf, 0x12, 0xdc, 0x08, 0x85, 0x19, 0x6e, 0x64, 0x22, 0xdc,
	0x79, 0xee, 0x5d, 0x74, 0xed, 0x27, 0xe8, 0xe4, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe3, 0x9a,
	0xea, 0xd3, 0xc8, 0x04, 0x00, 0x00,
}
