// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/db/srv/proto/db/db.proto
// DO NOT EDIT!

/*
Package go_micro_srv_db is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/db/srv/proto/db/db.proto

It has these top-level messages:
	DocRef
	CreateRequest
	CreateResponse
	BulkCreateRequest
	BulkCreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	CreateIndexWithSettingsRequest
	CreateIndexWithSettingsResponse
	PutMappingFromJSONRequest
	PutMappingFromJSONResponse
	StatusRequest
	StatusResponse
*/
package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DocRef struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DocRef) Reset()                    { *m = DocRef{} }
func (m *DocRef) String() string            { return proto.CompactTextString(m) }
func (*DocRef) ProtoMessage()               {}
func (*DocRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type BulkCreateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *BulkCreateRequest) Reset()                    { *m = BulkCreateRequest{} }
func (m *BulkCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkCreateRequest) ProtoMessage()               {}
func (*BulkCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type BulkCreateResponse struct {
}

func (m *BulkCreateResponse) Reset()                    { *m = BulkCreateResponse{} }
func (m *BulkCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkCreateResponse) ProtoMessage()               {}
func (*BulkCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type ReadRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type ReadResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type UpdateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type CreateIndexWithSettingsRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Settings string `protobuf:"bytes,2,opt,name=settings" json:"settings,omitempty"`
}

func (m *CreateIndexWithSettingsRequest) Reset()                    { *m = CreateIndexWithSettingsRequest{} }
func (m *CreateIndexWithSettingsRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIndexWithSettingsRequest) ProtoMessage()               {}
func (*CreateIndexWithSettingsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type CreateIndexWithSettingsResponse struct {
}

func (m *CreateIndexWithSettingsResponse) Reset()         { *m = CreateIndexWithSettingsResponse{} }
func (m *CreateIndexWithSettingsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateIndexWithSettingsResponse) ProtoMessage()    {}
func (*CreateIndexWithSettingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

type PutMappingFromJSONRequest struct {
	Index   string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type    string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Mapping string `protobuf:"bytes,3,opt,name=mapping" json:"mapping,omitempty"`
}

func (m *PutMappingFromJSONRequest) Reset()                    { *m = PutMappingFromJSONRequest{} }
func (m *PutMappingFromJSONRequest) String() string            { return proto.CompactTextString(m) }
func (*PutMappingFromJSONRequest) ProtoMessage()               {}
func (*PutMappingFromJSONRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type PutMappingFromJSONResponse struct {
}

func (m *PutMappingFromJSONResponse) Reset()                    { *m = PutMappingFromJSONResponse{} }
func (m *PutMappingFromJSONResponse) String() string            { return proto.CompactTextString(m) }
func (*PutMappingFromJSONResponse) ProtoMessage()               {}
func (*PutMappingFromJSONResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type StatusResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func init() {
	proto.RegisterType((*DocRef)(nil), "go.micro.srv.db.DocRef")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.db.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.db.CreateResponse")
	proto.RegisterType((*BulkCreateRequest)(nil), "go.micro.srv.db.BulkCreateRequest")
	proto.RegisterType((*BulkCreateResponse)(nil), "go.micro.srv.db.BulkCreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.db.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.db.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.db.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.db.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.db.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.db.DeleteResponse")
	proto.RegisterType((*CreateIndexWithSettingsRequest)(nil), "go.micro.srv.db.CreateIndexWithSettingsRequest")
	proto.RegisterType((*CreateIndexWithSettingsResponse)(nil), "go.micro.srv.db.CreateIndexWithSettingsResponse")
	proto.RegisterType((*PutMappingFromJSONRequest)(nil), "go.micro.srv.db.PutMappingFromJSONRequest")
	proto.RegisterType((*PutMappingFromJSONResponse)(nil), "go.micro.srv.db.PutMappingFromJSONResponse")
	proto.RegisterType((*StatusRequest)(nil), "go.micro.srv.db.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "go.micro.srv.db.StatusResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Elastic service

type ElasticClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	CreateIndexWithSettings(ctx context.Context, in *CreateIndexWithSettingsRequest, opts ...client.CallOption) (*CreateIndexWithSettingsResponse, error)
	PutMappingFromJSON(ctx context.Context, in *PutMappingFromJSONRequest, opts ...client.CallOption) (*PutMappingFromJSONRequest, error)
	Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error)
}

type elasticClient struct {
	c           client.Client
	serviceName string
}

func NewElasticClient(serviceName string, c client.Client) ElasticClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.db"
	}
	return &elasticClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *elasticClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) CreateIndexWithSettings(ctx context.Context, in *CreateIndexWithSettingsRequest, opts ...client.CallOption) (*CreateIndexWithSettingsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.CreateIndexWithSettings", in)
	out := new(CreateIndexWithSettingsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) PutMappingFromJSON(ctx context.Context, in *PutMappingFromJSONRequest, opts ...client.CallOption) (*PutMappingFromJSONRequest, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.PutMappingFromJSON", in)
	out := new(PutMappingFromJSONRequest)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *elasticClient) Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Elastic.Status", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Elastic service

type ElasticHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	CreateIndexWithSettings(context.Context, *CreateIndexWithSettingsRequest, *CreateIndexWithSettingsResponse) error
	PutMappingFromJSON(context.Context, *PutMappingFromJSONRequest, *PutMappingFromJSONRequest) error
	Status(context.Context, *StatusRequest, *StatusResponse) error
}

func RegisterElasticHandler(s server.Server, hdlr ElasticHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Elastic{hdlr}, opts...))
}

type Elastic struct {
	ElasticHandler
}

func (h *Elastic) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.ElasticHandler.Create(ctx, in, out)
}

func (h *Elastic) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.ElasticHandler.Read(ctx, in, out)
}

func (h *Elastic) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.ElasticHandler.Update(ctx, in, out)
}

func (h *Elastic) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.ElasticHandler.Delete(ctx, in, out)
}

func (h *Elastic) CreateIndexWithSettings(ctx context.Context, in *CreateIndexWithSettingsRequest, out *CreateIndexWithSettingsResponse) error {
	return h.ElasticHandler.CreateIndexWithSettings(ctx, in, out)
}

func (h *Elastic) PutMappingFromJSON(ctx context.Context, in *PutMappingFromJSONRequest, out *PutMappingFromJSONRequest) error {
	return h.ElasticHandler.PutMappingFromJSON(ctx, in, out)
}

func (h *Elastic) Status(ctx context.Context, in *StatusRequest, out *StatusResponse) error {
	return h.ElasticHandler.Status(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/db/srv/proto/db/db.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 488 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x95, 0xdf, 0x6e, 0xd3, 0x30,
	0x14, 0xc6, 0xbb, 0x11, 0x32, 0x38, 0xd0, 0x0e, 0xac, 0x09, 0x42, 0x34, 0x36, 0xf0, 0x05, 0x9a,
	0xb8, 0x48, 0x10, 0x7b, 0x83, 0xb1, 0x81, 0x0a, 0xe2, 0x8f, 0x52, 0x21, 0xae, 0x10, 0x72, 0x62,
	0xb7, 0x44, 0x4d, 0x62, 0x13, 0x3b, 0x08, 0xb8, 0xe0, 0xa9, 0x79, 0x00, 0x92, 0xd8, 0x29, 0x4d,
	0x9b, 0x20, 0x0a, 0xf4, 0xce, 0xe7, 0xf8, 0xf4, 0xf7, 0x9d, 0x73, 0xf2, 0x59, 0x85, 0xd3, 0x59,
	0xac, 0x3e, 0x16, 0xa1, 0x17, 0xf1, 0xd4, 0x9f, 0x93, 0x6f, 0xbc, 0x10, 0xbe, 0x48, 0x88, 0x9a,
	0xf2, 0x3c, 0xf5, 0x69, 0xe8, 0xcb, 0xfc, 0xb3, 0x2f, 0x72, 0xae, 0x78, 0x15, 0xd0, 0xd0, 0xab,
	0xcf, 0x68, 0x7f, 0xc6, 0xbd, 0x34, 0x8e, 0x72, 0xee, 0x95, 0xf7, 0x1e, 0x0d, 0xf1, 0x19, 0xd8,
	0xe7, 0x3c, 0x0a, 0xd8, 0x14, 0x1d, 0xc0, 0xe5, 0x38, 0xa3, 0xec, 0x8b, 0xb3, 0x73, 0x6f, 0xe7,
	0xe4, 0x6a, 0xa0, 0x03, 0x84, 0xc0, 0x52, 0x5f, 0x05, 0x73, 0x76, 0xeb, 0x64, 0x7d, 0x46, 0x23,
	0xd8, 0x8d, 0xa9, 0x73, 0xa9, 0xce, 0x94, 0x27, 0xfc, 0x1e, 0x86, 0x4f, 0x72, 0x46, 0x14, 0x0b,
	0xd8, 0xa7, 0x82, 0x49, 0xf5, 0xf7, 0xa8, 0xaa, 0x86, 0x12, 0x45, 0x1c, 0x4b, 0xd7, 0x54, 0x67,
	0x7c, 0x03, 0x46, 0x0d, 0x5e, 0x0a, 0x9e, 0x49, 0x86, 0x09, 0xdc, 0x3c, 0x2b, 0x92, 0xf9, 0x36,
	0x45, 0x0f, 0x00, 0x2d, 0x4b, 0x18, 0xe1, 0x67, 0x70, 0x2d, 0x60, 0x84, 0xfe, 0xb3, 0x24, 0x7e,
	0x00, 0xd7, 0x35, 0x48, 0x83, 0xd1, 0x2d, 0xb0, 0x73, 0x26, 0x8b, 0x44, 0x19, 0x94, 0x89, 0xaa,
	0xd5, 0xbe, 0x15, 0x74, 0x9b, 0xab, 0x6d, 0xf0, 0x66, 0xc2, 0x31, 0x0c, 0xcf, 0x59, 0xc2, 0xfe,
	0x83, 0x60, 0x05, 0x6f, 0x50, 0x06, 0x1e, 0xc0, 0x91, 0x5e, 0xe8, 0xb8, 0x82, 0xbc, 0x2b, 0xfd,
	0x3b, 0x61, 0x4a, 0xc5, 0xd9, 0x4c, 0xfe, 0x5e, 0xcd, 0x85, 0x2b, 0xd2, 0x14, 0x1a, 0xc5, 0x45,
	0x8c, 0xef, 0xc3, 0x71, 0x2f, 0xd3, 0xc8, 0x7e, 0x80, 0x3b, 0x6f, 0x0a, 0xf5, 0x92, 0x08, 0x51,
	0xa6, 0x9f, 0xe6, 0x3c, 0x7d, 0x3e, 0x79, 0xfd, 0x6a, 0xf3, 0xf9, 0x1c, 0xd8, 0x4b, 0x35, 0xc3,
	0x0c, 0xd9, 0x84, 0xf8, 0x10, 0xdc, 0x2e, 0x01, 0x23, 0xbf, 0x0f, 0xc3, 0x89, 0x22, 0xaa, 0x68,
	0x86, 0xc4, 0x27, 0x30, 0x6a, 0x12, 0xbf, 0x3e, 0xbf, 0xac, 0x33, 0xcd, 0xe7, 0xd7, 0xd1, 0xe3,
	0x1f, 0x16, 0xec, 0x5d, 0x24, 0x44, 0xaa, 0x38, 0x42, 0x2f, 0xc0, 0xd6, 0x83, 0xa2, 0x23, 0x6f,
	0xe5, 0x15, 0x7b, 0xad, 0x97, 0xe0, 0x1e, 0xf7, 0xde, 0x9b, 0x8e, 0x06, 0xe8, 0x02, 0xac, 0xca,
	0x7f, 0xe8, 0x70, 0xad, 0x74, 0xc9, 0xdf, 0xee, 0xdd, 0x9e, 0xdb, 0x05, 0xa6, 0xec, 0x49, 0xfb,
	0xa7, 0xa3, 0xa7, 0x96, 0x6f, 0x3b, 0x7a, 0x5a, 0x31, 0x5e, 0x0d, 0xd3, 0x7e, 0xe9, 0x80, 0xb5,
	0x3c, 0xd9, 0x01, 0x5b, 0x31, 0xda, 0x00, 0x7d, 0x87, 0xdb, 0x3d, 0xb6, 0x40, 0x7e, 0xcf, 0x7a,
	0xfa, 0x4c, 0xe9, 0x3e, 0xfa, 0xf3, 0x1f, 0x2c, 0xf4, 0x33, 0x40, 0xeb, 0x96, 0x40, 0x0f, 0xd7,
	0x48, 0xbd, 0xc6, 0x74, 0x37, 0xa8, 0xd5, 0xcb, 0xd3, 0x9e, 0xea, 0x58, 0x5e, 0xcb, 0x7d, 0x1d,
	0xcb, 0x6b, 0x9b, 0x11, 0x0f, 0x42, 0xbb, 0xfe, 0xb3, 0x38, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff,
	0x3f, 0x01, 0x08, 0x04, 0x63, 0x06, 0x00, 0x00,
}
