// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/db/srv/proto/db/db.proto
// DO NOT EDIT!

package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CreateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type ReadRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ReadResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type UpdateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type DeleteRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type DeleteByQueryRequest struct {
	Indexes  []string `protobuf:"bytes,1,rep,name=indexes" json:"indexes,omitempty"`
	Types    []string `protobuf:"bytes,2,rep,name=types" json:"types,omitempty"`
	Term     string   `protobuf:"bytes,3,opt,name=term" json:"term,omitempty"`
	Category string   `protobuf:"bytes,4,opt,name=category" json:"category,omitempty"`
	Url      string   `protobuf:"bytes,5,opt,name=url" json:"url,omitempty"`
	Depth    int64    `protobuf:"varint,6,opt,name=depth" json:"depth,omitempty"`
	FileType string   `protobuf:"bytes,7,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
	LastSeen int64    `protobuf:"varint,8,opt,name=last_seen,json=lastSeen" json:"last_seen,omitempty"`
}

func (m *DeleteByQueryRequest) Reset()                    { *m = DeleteByQueryRequest{} }
func (m *DeleteByQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteByQueryRequest) ProtoMessage()               {}
func (*DeleteByQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type DeleteByQueryResponse struct {
}

func (m *DeleteByQueryResponse) Reset()                    { *m = DeleteByQueryResponse{} }
func (m *DeleteByQueryResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteByQueryResponse) ProtoMessage()               {}
func (*DeleteByQueryResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type SearchRequest struct {
	Index                string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Term                 string `protobuf:"bytes,2,opt,name=term" json:"term,omitempty"`
	From                 int64  `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	Size                 int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Category             string `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	Url                  string `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Depth                int64  `protobuf:"varint,7,opt,name=depth" json:"depth,omitempty"`
	Type                 string `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	FileType             string `protobuf:"bytes,9,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
	UserId               string `protobuf:"bytes,10,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	LastSeen             int64  `protobuf:"varint,11,opt,name=last_seen,json=lastSeen" json:"last_seen,omitempty"`
	Access               string `protobuf:"bytes,12,opt,name=access" json:"access,omitempty"`
	NoKazoupFileOriginal bool   `protobuf:"varint,13,opt,name=no_kazoup_file_original,json=noKazoupFileOriginal" json:"no_kazoup_file_original,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

type SearchByIdRequest struct {
	Index  string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id     string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	UserId string `protobuf:"bytes,4,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SearchByIdRequest) Reset()                    { *m = SearchByIdRequest{} }
func (m *SearchByIdRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchByIdRequest) ProtoMessage()               {}
func (*SearchByIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

type SearchByIdResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
}

func (m *SearchByIdResponse) Reset()                    { *m = SearchByIdResponse{} }
func (m *SearchByIdResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchByIdResponse) ProtoMessage()               {}
func (*SearchByIdResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type HealthRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

type HealthResponse struct {
	Status int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.db.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.db.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.db.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.db.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.db.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.db.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.db.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.db.DeleteResponse")
	proto.RegisterType((*DeleteByQueryRequest)(nil), "go.micro.srv.db.DeleteByQueryRequest")
	proto.RegisterType((*DeleteByQueryResponse)(nil), "go.micro.srv.db.DeleteByQueryResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.db.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.db.SearchResponse")
	proto.RegisterType((*SearchByIdRequest)(nil), "go.micro.srv.db.SearchByIdRequest")
	proto.RegisterType((*SearchByIdResponse)(nil), "go.micro.srv.db.SearchByIdResponse")
	proto.RegisterType((*HealthRequest)(nil), "go.micro.srv.db.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "go.micro.srv.db.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DB service

type DBClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	DeleteByQuery(ctx context.Context, in *DeleteByQueryRequest, opts ...client.CallOption) (*DeleteByQueryResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	SearchById(ctx context.Context, in *SearchByIdRequest, opts ...client.CallOption) (*SearchByIdResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
}

type dBClient struct {
	c           client.Client
	serviceName string
}

func NewDBClient(serviceName string, c client.Client) DBClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.db"
	}
	return &dBClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dBClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) DeleteByQuery(ctx context.Context, in *DeleteByQueryRequest, opts ...client.CallOption) (*DeleteByQueryResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.DeleteByQuery", in)
	out := new(DeleteByQueryResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) SearchById(ctx context.Context, in *SearchByIdRequest, opts ...client.CallOption) (*SearchByIdResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.SearchById", in)
	out := new(SearchByIdResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dBClient) Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DB.Health", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DB service

type DBHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	DeleteByQuery(context.Context, *DeleteByQueryRequest, *DeleteByQueryResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	SearchById(context.Context, *SearchByIdRequest, *SearchByIdResponse) error
	Health(context.Context, *HealthRequest, *HealthResponse) error
}

func RegisterDBHandler(s server.Server, hdlr DBHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DB{hdlr}, opts...))
}

type DB struct {
	DBHandler
}

func (h *DB) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.DBHandler.Create(ctx, in, out)
}

func (h *DB) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.DBHandler.Read(ctx, in, out)
}

func (h *DB) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.DBHandler.Update(ctx, in, out)
}

func (h *DB) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.DBHandler.Delete(ctx, in, out)
}

func (h *DB) DeleteByQuery(ctx context.Context, in *DeleteByQueryRequest, out *DeleteByQueryResponse) error {
	return h.DBHandler.DeleteByQuery(ctx, in, out)
}

func (h *DB) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.DBHandler.Search(ctx, in, out)
}

func (h *DB) SearchById(ctx context.Context, in *SearchByIdRequest, out *SearchByIdResponse) error {
	return h.DBHandler.SearchById(ctx, in, out)
}

func (h *DB) Health(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.DBHandler.Health(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/db/srv/proto/db/db.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 693 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x55, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x6e, 0xe2, 0x7c, 0x75, 0xda, 0xf4, 0xed, 0xbb, 0x2a, 0xd4, 0x0a, 0x9f, 0x72, 0x45, 0xc5,
	0x01, 0x39, 0x12, 0x15, 0x37, 0x4e, 0xa5, 0x7c, 0x54, 0x3d, 0x20, 0x5c, 0x10, 0x27, 0x14, 0x36,
	0xf6, 0x26, 0xb5, 0x70, 0xbc, 0x66, 0x77, 0x8d, 0x48, 0xff, 0x00, 0x7f, 0x11, 0x89, 0x3f, 0xc3,
	0x7e, 0xd8, 0x8d, 0x37, 0x38, 0xcd, 0xa1, 0x70, 0x9b, 0x99, 0x9d, 0x7d, 0x66, 0x9e, 0xf1, 0xec,
	0x63, 0x38, 0x9a, 0xc6, 0xe2, 0x22, 0x1f, 0xfb, 0x21, 0x9d, 0x0d, 0xbf, 0xe0, 0x4b, 0x9a, 0x67,
	0xc3, 0x2c, 0xc1, 0x62, 0x42, 0xd9, 0x6c, 0x18, 0x8d, 0x87, 0x9c, 0x7d, 0x1b, 0x66, 0x8c, 0x0a,
	0xaa, 0x9c, 0x68, 0xec, 0x6b, 0x1b, 0xfd, 0x37, 0xa5, 0xfe, 0x2c, 0x0e, 0x19, 0xf5, 0xe5, 0xb9,
	0x1f, 0x8d, 0xbd, 0x4f, 0xd0, 0x7f, 0xc1, 0x08, 0x16, 0x24, 0x20, 0x5f, 0x73, 0xc2, 0x05, 0xda,
	0x83, 0x76, 0x9c, 0x46, 0xe4, 0xbb, 0xdb, 0x78, 0xd8, 0x78, 0xbc, 0x19, 0x18, 0x07, 0x21, 0x68,
	0x89, 0x79, 0x46, 0xdc, 0xa6, 0x0e, 0x6a, 0x1b, 0xed, 0x40, 0x33, 0x8e, 0x5c, 0x47, 0x47, 0xa4,
	0xa5, 0x72, 0x22, 0x2c, 0xb0, 0xdb, 0x32, 0x39, 0xca, 0xf6, 0x76, 0x61, 0xa7, 0x84, 0xe7, 0x19,
	0x4d, 0x39, 0xf1, 0x5e, 0xc3, 0x56, 0x40, 0x70, 0x74, 0xe3, 0x72, 0xde, 0x21, 0x6c, 0x1b, 0x20,
	0x03, 0x8c, 0x6e, 0x43, 0x87, 0x11, 0x9e, 0x27, 0xa2, 0x80, 0x2a, 0x3c, 0xc5, 0xf0, 0x43, 0x16,
	0xfd, 0x4b, 0x86, 0x25, 0x7c, 0xc1, 0xf0, 0x14, 0xfa, 0x27, 0x24, 0x21, 0x7f, 0xa1, 0xa0, 0x02,
	0x2f, 0xa1, 0x0a, 0xf0, 0x9f, 0x0d, 0xd8, 0x33, 0xa1, 0xe3, 0xf9, 0xbb, 0x9c, 0xb0, 0x79, 0x59,
	0xc4, 0x85, 0xae, 0xc6, 0x25, 0x5c, 0x96, 0x71, 0xe4, 0xfd, 0xd2, 0x55, 0xe5, 0x15, 0x38, 0x97,
	0x95, 0x54, 0xdc, 0x38, 0xba, 0x3c, 0x61, 0xb3, 0xa2, 0x98, 0xb6, 0xd1, 0x00, 0x7a, 0xa1, 0x64,
	0x32, 0xa5, 0x6c, 0x5e, 0x70, 0xbc, 0xf2, 0xd1, 0x2e, 0x38, 0x39, 0x4b, 0xdc, 0xb6, 0x0e, 0x2b,
	0x53, 0xe1, 0x46, 0x24, 0x13, 0x17, 0x6e, 0x47, 0xc6, 0x9c, 0xc0, 0x38, 0xe8, 0x0e, 0x6c, 0x4e,
	0xe2, 0x84, 0x8c, 0x34, 0xb7, 0xae, 0x01, 0x51, 0x81, 0xf7, 0x8a, 0x9f, 0x3c, 0x4c, 0x30, 0x17,
	0x23, 0x4e, 0x48, 0xea, 0xf6, 0xf4, 0xb5, 0x9e, 0x0a, 0x9c, 0x4b, 0xdf, 0xdb, 0x87, 0x5b, 0x4b,
	0xcc, 0x0a, 0xce, 0xbf, 0x9a, 0xd0, 0x3f, 0x27, 0x98, 0x85, 0x17, 0xeb, 0x27, 0xaa, 0x28, 0x35,
	0x2b, 0x94, 0x64, 0x6c, 0xc2, 0xa8, 0xa1, 0xe9, 0x04, 0xda, 0x56, 0x31, 0x1e, 0x5f, 0x12, 0x4d,
	0x51, 0xc6, 0x94, 0x6d, 0x51, 0x6f, 0xd7, 0x53, 0xef, 0xd4, 0x50, 0xef, 0x56, 0xa9, 0x97, 0x5f,
	0xb4, 0x57, 0xf9, 0xa2, 0xd6, 0x38, 0x36, 0x97, 0xc6, 0xb1, 0x0f, 0xdd, 0x9c, 0x13, 0x36, 0x92,
	0xdf, 0x1c, 0xcc, 0xce, 0x2a, 0xf7, 0x34, 0xb2, 0xe7, 0xb4, 0x65, 0xcf, 0x49, 0x2d, 0x3a, 0x0e,
	0x43, 0xc2, 0xb9, 0xbb, 0x6d, 0x2e, 0x19, 0x0f, 0x3d, 0x83, 0xfd, 0x94, 0x8e, 0x8c, 0x14, 0x8c,
	0x74, 0x51, 0xca, 0xe2, 0x69, 0x9c, 0xe2, 0xc4, 0xed, 0xcb, 0xc4, 0x5e, 0xb0, 0x97, 0xd2, 0x33,
	0x7d, 0xfa, 0x4a, 0x1e, 0xbe, 0x2d, 0xce, 0xbc, 0xe7, 0xb0, 0x53, 0x0e, 0xf7, 0xfa, 0x97, 0xa4,
	0xf8, 0xc5, 0xe9, 0x84, 0x96, 0xf3, 0x55, 0xb6, 0x37, 0x81, 0xff, 0xcd, 0xed, 0xe3, 0xf9, 0xe9,
	0xcd, 0x1f, 0x75, 0x75, 0x22, 0xad, 0xea, 0x44, 0xbc, 0x27, 0x80, 0xaa, 0x75, 0xd6, 0xbc, 0xf9,
	0x03, 0xe8, 0xbf, 0x21, 0x38, 0x11, 0x57, 0x0b, 0x53, 0xd6, 0x6e, 0x2c, 0x6a, 0x2b, 0xe2, 0x65,
	0xd2, 0x02, 0x8e, 0x0b, 0x2c, 0x72, 0xae, 0xf3, 0x9c, 0xa0, 0xf0, 0xea, 0x88, 0x3f, 0xfd, 0xd1,
	0x86, 0xe6, 0xc9, 0x31, 0x3a, 0x83, 0x8e, 0x11, 0x38, 0x74, 0xdf, 0x5f, 0xd2, 0x56, 0xdf, 0x12,
	0xd6, 0xc1, 0x83, 0x95, 0xe7, 0xc5, 0x9a, 0x6f, 0xa0, 0x97, 0xd0, 0x52, 0x92, 0x86, 0xee, 0xfe,
	0x91, 0x5a, 0x91, 0xcc, 0xc1, 0xbd, 0x15, 0xa7, 0x57, 0x30, 0xb2, 0x27, 0x23, 0x49, 0x35, 0x3d,
	0x59, 0x52, 0x58, 0xd3, 0xd3, 0x92, 0x96, 0x69, 0x30, 0xf3, 0x2a, 0x6b, 0xc0, 0x2c, 0x99, 0xab,
	0x01, 0x5b, 0xd2, 0xae, 0x0d, 0xf4, 0xb9, 0x94, 0xc6, 0xe2, 0x89, 0xa3, 0x47, 0x2b, 0xee, 0xd8,
	0xe2, 0x36, 0x38, 0x5c, 0x97, 0x56, 0x6d, 0xd7, 0xec, 0x49, 0x4d, 0xbb, 0x96, 0x86, 0xd4, 0xb4,
	0x6b, 0x3f, 0x03, 0x09, 0xf6, 0x11, 0x60, 0xb1, 0x74, 0xc8, 0x5b, 0x71, 0xa1, 0xb2, 0xf9, 0x83,
	0x83, 0x6b, 0x73, 0xaa, 0x5d, 0x9a, 0xd5, 0xab, 0xe9, 0xd2, 0x5a, 0xdc, 0x9a, 0x2e, 0xed, 0x9d,
	0xf5, 0x36, 0xc6, 0x1d, 0xfd, 0x6b, 0x3f, 0xfa, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x71, 0x44, 0xe4,
	0x62, 0x11, 0x08, 0x00, 0x00,
}
