// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/search/srv/proto/search/messages.proto
// DO NOT EDIT!

/*
Package go_micro_srv_search_search is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/search/srv/proto/search/messages.proto
	github.com/kazoup/platform/search/srv/proto/search/search.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
	Aggregation
	AggregateRequest
	AggregateResponse
*/
package go_micro_srv_search_search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Term     string `protobuf:"bytes,2,opt,name=term" json:"term,omitempty"`
	From     int64  `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	Size     int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Category string `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	Url      string `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Depth    int64  `protobuf:"varint,7,opt,name=depth" json:"depth,omitempty"`
	Type     string `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	FileType string `protobuf:"bytes,9,opt,name=file_type,json=fileType" json:"file_type,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Aggregation struct {
	AggregationType string `protobuf:"bytes,1,opt,name=aggregation_type,json=aggregationType" json:"aggregation_type,omitempty"`
	Field           string `protobuf:"bytes,2,opt,name=field" json:"field,omitempty"`
}

func (m *Aggregation) Reset()                    { *m = Aggregation{} }
func (m *Aggregation) String() string            { return proto.CompactTextString(m) }
func (*Aggregation) ProtoMessage()               {}
func (*Aggregation) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type AggregateRequest struct {
	Filters *SearchRequest `protobuf:"bytes,1,opt,name=filters" json:"filters,omitempty"`
	Agg     []*Aggregation `protobuf:"bytes,2,rep,name=agg" json:"agg,omitempty"`
}

func (m *AggregateRequest) Reset()                    { *m = AggregateRequest{} }
func (m *AggregateRequest) String() string            { return proto.CompactTextString(m) }
func (*AggregateRequest) ProtoMessage()               {}
func (*AggregateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AggregateRequest) GetFilters() *SearchRequest {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *AggregateRequest) GetAgg() []*Aggregation {
	if m != nil {
		return m.Agg
	}
	return nil
}

type AggregateResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *AggregateResponse) Reset()                    { *m = AggregateResponse{} }
func (m *AggregateResponse) String() string            { return proto.CompactTextString(m) }
func (*AggregateResponse) ProtoMessage()               {}
func (*AggregateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.search.search.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.search.search.SearchResponse")
	proto.RegisterType((*Aggregation)(nil), "go.micro.srv.search.search.Aggregation")
	proto.RegisterType((*AggregateRequest)(nil), "go.micro.srv.search.search.AggregateRequest")
	proto.RegisterType((*AggregateResponse)(nil), "go.micro.srv.search.search.AggregateResponse")
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/search/srv/proto/search/messages.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x52, 0xcb, 0x4e, 0xc3, 0x30,
	0x10, 0x54, 0x48, 0x9f, 0x5b, 0x01, 0xc5, 0x42, 0xc8, 0x2a, 0x17, 0x94, 0x0b, 0xf4, 0x92, 0x48,
	0x70, 0x42, 0x42, 0x42, 0x15, 0x77, 0x0e, 0x81, 0x3b, 0x4a, 0xd3, 0x4d, 0x6a, 0x91, 0xc4, 0xc1,
	0x76, 0x10, 0xed, 0x67, 0xf0, 0x71, 0x7c, 0x0f, 0x7e, 0x24, 0x50, 0x0e, 0x20, 0x71, 0xca, 0xcc,
	0xc4, 0x3b, 0xb3, 0xbb, 0x36, 0x2c, 0x72, 0xa6, 0xd6, 0xcd, 0x32, 0x4c, 0x79, 0x19, 0x3d, 0x27,
	0x5b, 0xde, 0xd4, 0x51, 0x5d, 0x24, 0x2a, 0xe3, 0xa2, 0x8c, 0x24, 0x26, 0x22, 0x5d, 0x47, 0x52,
	0xbc, 0x46, 0xb5, 0xe0, 0x8a, 0x77, 0x42, 0x89, 0x52, 0x26, 0x39, 0xca, 0xd0, 0xaa, 0x64, 0x96,
	0xf3, 0xb0, 0x64, 0xa9, 0xe0, 0xa1, 0x3e, 0x19, 0xba, 0x33, 0xed, 0x27, 0xf8, 0xf0, 0x60, 0xff,
	0xc1, 0xc2, 0x18, 0x5f, 0x1a, 0x94, 0x8a, 0x1c, 0x43, 0x9f, 0x55, 0x2b, 0x7c, 0xa3, 0xde, 0x99,
	0x77, 0x31, 0x8e, 0x1d, 0x21, 0x04, 0x7a, 0x0a, 0x45, 0x49, 0xf7, 0xac, 0x68, 0xb1, 0xd1, 0x32,
	0xc1, 0x4b, 0xea, 0x6b, 0xcd, 0x8f, 0x2d, 0x36, 0x9a, 0x64, 0x5b, 0xa4, 0x3d, 0xa7, 0x19, 0x4c,
	0x66, 0x30, 0x4a, 0x13, 0x85, 0x39, 0x17, 0x1b, 0xda, 0xb7, 0xf5, 0x5f, 0x9c, 0x4c, 0xc1, 0x6f,
	0x44, 0x41, 0x07, 0x56, 0x36, 0xd0, 0xe4, 0xaf, 0xb0, 0x56, 0x6b, 0x3a, 0xb4, 0x16, 0x8e, 0xd8,
	0xfc, 0x4d, 0x8d, 0x74, 0xd4, 0xe6, 0x6b, 0x4c, 0x4e, 0x61, 0x9c, 0xb1, 0x02, 0x9f, 0xec, 0x8f,
	0xb1, 0x33, 0x36, 0xc2, 0xa3, 0xe6, 0xc1, 0x0d, 0x1c, 0x74, 0x73, 0xc9, 0x9a, 0x57, 0x12, 0xc9,
	0x09, 0x0c, 0x04, 0xca, 0xa6, 0x50, 0xed, 0x64, 0x2d, 0x33, 0xd6, 0xac, 0xca, 0x78, 0x37, 0x9a,
	0xc1, 0xc1, 0x3d, 0x4c, 0x16, 0x79, 0x2e, 0x30, 0x4f, 0x14, 0xe3, 0x15, 0x99, 0xc3, 0x34, 0xf9,
	0xa6, 0x2e, 0xd0, 0x99, 0x1c, 0xee, 0xe8, 0x26, 0xd7, 0xb4, 0x9f, 0x31, 0x2c, 0x56, 0xad, 0x9d,
	0x23, 0xc1, 0xbb, 0x07, 0xd3, 0xce, 0x10, 0xbb, 0x4d, 0xdf, 0xc1, 0x50, 0xb7, 0xab, 0x57, 0x29,
	0xad, 0xd9, 0xe4, 0x72, 0x1e, 0xfe, 0x7e, 0x53, 0xe1, 0x8f, 0x5b, 0x8a, 0xbb, 0x4a, 0x72, 0x0d,
	0xbe, 0x6e, 0x41, 0xa7, 0xf9, 0xda, 0xe0, 0xfc, 0x2f, 0x83, 0x9d, 0x81, 0x62, 0x53, 0x13, 0xdc,
	0xc2, 0xd1, 0x4e, 0x4f, 0xff, 0xdf, 0xd2, 0x72, 0x60, 0xdf, 0xd7, 0xd5, 0x67, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x7d, 0x4f, 0xec, 0x28, 0xa4, 0x02, 0x00, 0x00,
}
