// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/search/srv/proto/search/search.proto
// DO NOT EDIT!

package go_micro_srv_search_search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Search service

type SearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Aggregate(ctx context.Context, in *AggregateRequest, opts ...client.CallOption) (*AggregateResponse, error)
}

type searchClient struct {
	c           client.Client
	serviceName string
}

func NewSearchClient(serviceName string, c client.Client) SearchClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.search.search"
	}
	return &searchClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *searchClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Search.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchClient) Aggregate(ctx context.Context, in *AggregateRequest, opts ...client.CallOption) (*AggregateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Search.Aggregate", in)
	out := new(AggregateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchHandler interface {
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Aggregate(context.Context, *AggregateRequest, *AggregateResponse) error
}

func RegisterSearchHandler(s server.Server, hdlr SearchHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Search{hdlr}, opts...))
}

type Search struct {
	SearchHandler
}

func (h *Search) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SearchHandler.Search(ctx, in, out)
}

func (h *Search) Aggregate(ctx context.Context, in *AggregateRequest, out *AggregateResponse) error {
	return h.SearchHandler.Aggregate(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/search/srv/proto/search/search.proto", fileDescriptor1)
}

var fileDescriptor1 = []byte{
	// 178 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x8f, 0x31, 0x0e, 0xc2, 0x30,
	0x0c, 0x45, 0x61, 0xa9, 0x44, 0xc7, 0x8c, 0x1d, 0xd9, 0x40, 0xe0, 0x48, 0x70, 0x00, 0xd4, 0x2b,
	0xc0, 0x09, 0xd2, 0xca, 0xa4, 0x05, 0x82, 0x83, 0x9d, 0x32, 0x70, 0x51, 0xae, 0x03, 0x4a, 0x69,
	0x36, 0x50, 0xc5, 0xf4, 0xa3, 0xff, 0x5f, 0xfe, 0x97, 0xf3, 0x9d, 0x6d, 0x43, 0xd3, 0x55, 0x50,
	0x93, 0xd3, 0x67, 0xf3, 0xa0, 0xce, 0x6b, 0x7f, 0x31, 0xe1, 0x48, 0xec, 0xb4, 0xa0, 0xe1, 0xba,
	0xd1, 0xc2, 0x77, 0xed, 0x99, 0x02, 0x25, 0x23, 0x0a, 0x44, 0x4f, 0x15, 0x96, 0xc0, 0xb5, 0x35,
	0x13, 0xbc, 0x39, 0xf8, 0x44, 0xbd, 0x14, 0xe5, 0x1f, 0xe5, 0x0e, 0x45, 0x8c, 0x45, 0xe9, 0xeb,
	0x37, 0xcf, 0x69, 0x9e, 0x1d, 0x62, 0xa2, 0x4c, 0x7a, 0x2d, 0xe0, 0xfb, 0x28, 0xf4, 0xcc, 0x1e,
	0x6f, 0x1d, 0x4a, 0x28, 0x96, 0x63, 0x50, 0xf1, 0x74, 0x15, 0x9c, 0x4f, 0xd4, 0x29, 0x9f, 0x95,
	0xd6, 0x32, 0x5a, 0x13, 0x50, 0xad, 0x7e, 0x7d, 0x4d, 0xd8, 0x30, 0xb4, 0x1e, 0x49, 0x0f, 0x5b,
	0x55, 0x16, 0x0f, 0xdc, 0xbe, 0x02, 0x00, 0x00, 0xff, 0xff, 0x81, 0x15, 0x4d, 0x60, 0x82, 0x01,
	0x00, 0x00,
}
