// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/search/srv/proto/search/search.proto
// DO NOT EDIT!

/*
Package go_micro_srv_search is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/search/srv/proto/search/search.proto

It has these top-level messages:
	SearchRequest
	SearchResponse
*/
package go_micro_srv_search

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SearchRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Term     string `protobuf:"bytes,2,opt,name=term" json:"term,omitempty"`
	From     int64  `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	Size     int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Category string `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	Url      string `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Depth    int64  `protobuf:"varint,7,opt,name=depth" json:"depth,omitempty"`
	Type     string `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.search.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.search.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Search service

type SearchClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type searchClient struct {
	c           client.Client
	serviceName string
}

func NewSearchClient(serviceName string, c client.Client) SearchClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.search"
	}
	return &searchClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *searchClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Search.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Search service

type SearchHandler interface {
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterSearchHandler(s server.Server, hdlr SearchHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Search{hdlr}, opts...))
}

type Search struct {
	SearchHandler
}

func (h *Search) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SearchHandler.Search(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/search/srv/proto/search/search.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0xc7, 0x8d, 0x69, 0x63, 0x5d, 0x50, 0x64, 0x15, 0x59, 0x7a, 0x92, 0x78, 0xf1, 0xb4, 0x01,
	0xbd, 0x0a, 0xbe, 0x43, 0x7a, 0xf6, 0x90, 0xa6, 0x93, 0x0f, 0x4c, 0x32, 0xeb, 0x7e, 0x88, 0xed,
	0x9b, 0xf9, 0x76, 0x66, 0x67, 0xd3, 0x80, 0x20, 0x3d, 0xe5, 0x37, 0xbf, 0xcc, 0xec, 0xfc, 0x19,
	0xf6, 0x56, 0xb7, 0xb6, 0x71, 0x5b, 0x59, 0x62, 0x9f, 0x7d, 0x14, 0x07, 0x74, 0x2a, 0x53, 0x5d,
	0x61, 0x2b, 0xd4, 0x7d, 0x66, 0xa0, 0xd0, 0x65, 0x93, 0x19, 0xfd, 0x95, 0x29, 0x8d, 0x16, 0x67,
	0x41, 0x1f, 0x49, 0x8e, 0xdf, 0xd6, 0x28, 0xfb, 0xb6, 0xd4, 0x28, 0xc7, 0x3e, 0x19, 0x7e, 0xa5,
	0x3f, 0x11, 0xbb, 0xda, 0x10, 0xe6, 0xf0, 0xe9, 0xc0, 0x58, 0x7e, 0xc7, 0x96, 0xed, 0xb0, 0x83,
	0x6f, 0x11, 0x3d, 0x44, 0x4f, 0x97, 0x79, 0x28, 0x38, 0x67, 0x0b, 0x0b, 0xba, 0x17, 0xe7, 0x24,
	0x89, 0xbd, 0xab, 0x34, 0xf6, 0x22, 0x1e, 0x5d, 0x9c, 0x13, 0x7b, 0x67, 0xda, 0x03, 0x88, 0x45,
	0x70, 0x9e, 0xf9, 0x9a, 0xad, 0xca, 0xc2, 0x42, 0x8d, 0x7a, 0x2f, 0x96, 0x34, 0x3f, 0xd7, 0xfc,
	0x86, 0xc5, 0x4e, 0x77, 0x22, 0x21, 0xed, 0xd1, 0xef, 0xdf, 0x81, 0xb2, 0x8d, 0xb8, 0xa0, 0x27,
	0x42, 0x41, 0xfb, 0xf7, 0x0a, 0xc4, 0x6a, 0xda, 0x3f, 0x72, 0xfa, 0xca, 0xae, 0x8f, 0xd1, 0x8d,
	0xc2, 0xc1, 0x00, 0xbf, 0x67, 0x89, 0x06, 0xe3, 0x3a, 0x3b, 0x85, 0x9f, 0x2a, 0x3f, 0xdd, 0x0e,
	0x15, 0x1e, 0xd3, 0x7b, 0x7e, 0x7e, 0x67, 0x49, 0x98, 0xe6, 0x9b, 0x99, 0x52, 0xf9, 0xcf, 0x8d,
	0xe4, 0x9f, 0xfb, 0xac, 0x1f, 0x4f, 0xf6, 0x84, 0x20, 0xe9, 0xd9, 0x36, 0xa1, 0xa3, 0xbf, 0xfc,
	0x06, 0x00, 0x00, 0xff, 0xff, 0xf3, 0x22, 0x4d, 0x0f, 0xb7, 0x01, 0x00, 0x00,
}
