// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/profile/srv/proto/profile/profile.proto
// DO NOT EDIT!

/*
Package go_micro_srv_profile is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/profile/srv/proto/profile/profile.proto
	github.com/kazoup/platform/profile/srv/proto/subscription/subscription.proto

It has these top-level messages:
	Profile
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	HealthRequest
	HealthResponse
	UpdateSubRequest
	UpdateSubResponse
*/
package go_micro_srv_profile

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Profile struct {
	Email   string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Profile string `protobuf:"bytes,2,opt,name=profile" json:"profile,omitempty"`
}

func (m *Profile) Reset()                    { *m = Profile{} }
func (m *Profile) String() string            { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()               {}
func (*Profile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ReadRequest struct {
	StripeId string `protobuf:"bytes,1,opt,name=stripe_id,json=stripeId" json:"stripe_id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ReadResponse struct {
	Profile *Profile `protobuf:"bytes,1,opt,name=profile" json:"profile,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetProfile() *Profile {
	if m != nil {
		return m.Profile
	}
	return nil
}

type UpdateRequest struct {
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type DeleteRequest struct {
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type HealthRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type HealthResponse struct {
	Status int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*Profile)(nil), "go.micro.srv.profile.Profile")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.profile.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.profile.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "go.micro.srv.profile.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "go.micro.srv.profile.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "go.micro.srv.profile.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "go.micro.srv.profile.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.profile.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.profile.DeleteResponse")
	proto.RegisterType((*HealthRequest)(nil), "go.micro.srv.profile.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "go.micro.srv.profile.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ProfileSrv service

type ProfileSrvClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
}

type profileSrvClient struct {
	c           client.Client
	serviceName string
}

func NewProfileSrvClient(serviceName string, c client.Client) ProfileSrvClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.profile"
	}
	return &profileSrvClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *profileSrvClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProfileSrv.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileSrvClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProfileSrv.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileSrvClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProfileSrv.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileSrvClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProfileSrv.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileSrvClient) Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.serviceName, "ProfileSrv.Health", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ProfileSrv service

type ProfileSrvHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Health(context.Context, *HealthRequest, *HealthResponse) error
}

func RegisterProfileSrvHandler(s server.Server, hdlr ProfileSrvHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&ProfileSrv{hdlr}, opts...))
}

type ProfileSrv struct {
	ProfileSrvHandler
}

func (h *ProfileSrv) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.ProfileSrvHandler.Create(ctx, in, out)
}

func (h *ProfileSrv) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.ProfileSrvHandler.Read(ctx, in, out)
}

func (h *ProfileSrv) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.ProfileSrvHandler.Update(ctx, in, out)
}

func (h *ProfileSrv) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.ProfileSrvHandler.Delete(ctx, in, out)
}

func (h *ProfileSrv) Health(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.ProfileSrvHandler.Health(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/profile/srv/proto/profile/profile.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x41, 0x10, 0xe4, 0x21, 0x68, 0x1a, 0x62, 0x08, 0xc6, 0x44, 0x8b, 0x07, 0xe3, 0x61,
	0x4b, 0xf0, 0x60, 0x4c, 0x3c, 0xa9, 0x89, 0x7a, 0xd2, 0xcc, 0x70, 0x36, 0x83, 0x15, 0x58, 0xdc,
	0xe8, 0x6c, 0x3b, 0x12, 0xfd, 0xcf, 0xfc, 0xef, 0x64, 0xed, 0x1b, 0x5a, 0xc2, 0x38, 0xf1, 0xfa,
	0xf1, 0xdb, 0xb7, 0xaf, 0xef, 0xcb, 0xe0, 0x6e, 0x1a, 0xaa, 0x59, 0x3a, 0x72, 0xc6, 0x3c, 0x76,
	0x3f, 0xfc, 0x6f, 0x9e, 0x26, 0x6e, 0x12, 0xf9, 0x6a, 0xc2, 0x45, 0xec, 0x26, 0x82, 0x4f, 0xc2,
	0x88, 0xb9, 0x52, 0x2c, 0xb2, 0x59, 0xf1, 0x95, 0x82, 0xbf, 0x8e, 0x56, 0x49, 0x67, 0xca, 0x9d,
	0x38, 0x1c, 0x0b, 0xee, 0x2c, 0x49, 0x07, 0xff, 0xa3, 0x37, 0x50, 0x7f, 0x35, 0x23, 0xe9, 0xc0,
	0x2e, 0x8b, 0xfd, 0x30, 0xea, 0x96, 0x4f, 0xcb, 0x17, 0x0d, 0xcf, 0x1c, 0x48, 0x17, 0xea, 0xc8,
	0x76, 0x77, 0xb4, 0x9e, 0x1f, 0xe9, 0x01, 0xb4, 0xee, 0x05, 0xf3, 0x15, 0xf3, 0xd8, 0x67, 0xca,
	0xa4, 0xa2, 0x87, 0xd0, 0xce, 0x05, 0x99, 0xf0, 0xb9, 0x64, 0xf4, 0x12, 0x9a, 0x1e, 0xf3, 0x03,
	0x04, 0xc8, 0x31, 0x34, 0xa4, 0x12, 0x61, 0xc2, 0xde, 0xc3, 0x00, 0xdf, 0xb2, 0x67, 0x84, 0xe7,
	0x80, 0x3e, 0xc2, 0xbe, 0x61, 0xcd, 0xb3, 0xe4, 0xfa, 0xef, 0xc5, 0x19, 0xda, 0x1c, 0x9c, 0x38,
	0x9b, 0x6e, 0xe0, 0x60, 0x7c, 0x2b, 0xd7, 0x30, 0x09, 0xec, 0x5c, 0xb9, 0x80, 0xb9, 0x96, 0xc8,
	0x03, 0x8b, 0x98, 0x85, 0xe4, 0x02, 0x22, 0x7d, 0x68, 0x3d, 0x31, 0x3f, 0x52, 0xb3, 0x3c, 0x3c,
	0x81, 0xaa, 0xfa, 0x4a, 0x18, 0xe6, 0xd6, 0x33, 0xbd, 0x85, 0x76, 0x0e, 0x61, 0xea, 0x23, 0xa8,
	0x49, 0xe5, 0xab, 0x54, 0x6a, 0xae, 0xe2, 0xe1, 0x29, 0x7b, 0x3a, 0x9c, 0x4f, 0x38, 0xee, 0x50,
	0xcf, 0x83, 0x9f, 0x0a, 0x00, 0xa6, 0x7f, 0x13, 0x0b, 0x32, 0x84, 0x9a, 0x59, 0x1f, 0xe9, 0x6f,
	0xbe, 0xa9, 0xb5, 0xed, 0xde, 0xf9, 0x76, 0x08, 0xaf, 0x51, 0x22, 0x2f, 0x50, 0xcd, 0xf6, 0x4a,
	0xce, 0x36, 0xf3, 0xff, 0xfa, 0xe9, 0xd1, 0x6d, 0xc8, 0xca, 0x70, 0x99, 0xd3, 0xac, 0xb3, 0x28,
	0xa7, 0xb5, 0xfd, 0xa2, 0x9c, 0x6b, 0x8d, 0x68, 0x5b, 0x53, 0x41, 0x91, 0xad, 0xd5, 0x58, 0x91,
	0xed, 0x5a, 0x8b, 0xda, 0xd6, 0x54, 0x54, 0x64, 0x6b, 0xb5, 0x5c, 0x64, 0x6b, 0xb7, 0x4c, 0x4b,
	0xa3, 0x9a, 0xfe, 0xa8, 0xae, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0x02, 0xa4, 0x41, 0xa8, 0x9a,
	0x03, 0x00, 0x00,
}
