apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: micro-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        name: micro-web
        app: micro-web
    spec:
      containers:
        - name: micro-web
          resources:
            limits:
              cpu: "200m"
          command: [
            "/micro",
            "--registry=consul",
            "--registry_address=$(REGISTRY_SERVICE_HOST)",
            "--web_namespace=com.kazoup.web",
            "--register_ttl=60",
            "--register_interval=30",
            "--web_cors=*",
            "--enable_tls",
            "--tls_cert_file=/secrets/tls.crt",
            "--tls_key_file=/secrets/tls.key",
            "--broker=nats",
            "--broker_address=nats:4222",
            "--transport=tcp",
            "web"
          ]
          image: eu.gcr.io/desktop-1470249894548/micro-web:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8082
            name: web-port
          volumeMounts: 
          - name: secrets
            mountPath: "/secrets"
            readOnly: true
      volumes:
      - name: secrets
        secret: 
         secretName: "ssl"
        
