// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/datasource/srv/proto/datasource/datasource.proto
// DO NOT EDIT!

/*
Package go_micro_srv_datasource is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/datasource/srv/proto/datasource/datasource.proto

It has these top-level messages:
	Endpoint
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
	ScanRequest
	ScanResponse
	Token
*/
package go_micro_srv_datasource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Endpoint struct {
	Id    string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url   string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Token *Token `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Endpoint) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type CreateRequest struct {
	Endpoint *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type CreateResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SearchRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Term     string `protobuf:"bytes,2,opt,name=term" json:"term,omitempty"`
	From     int64  `protobuf:"varint,3,opt,name=from" json:"from,omitempty"`
	Size     int64  `protobuf:"varint,4,opt,name=size" json:"size,omitempty"`
	Category string `protobuf:"bytes,5,opt,name=category" json:"category,omitempty"`
	Url      string `protobuf:"bytes,6,opt,name=url" json:"url,omitempty"`
	Depth    int64  `protobuf:"varint,7,opt,name=depth" json:"depth,omitempty"`
	Type     string `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchResponse struct {
	Result string `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type ScanRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ScanRequest) Reset()                    { *m = ScanRequest{} }
func (m *ScanRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()               {}
func (*ScanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ScanResponse struct {
}

func (m *ScanResponse) Reset()                    { *m = ScanResponse{} }
func (m *ScanResponse) String() string            { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()               {}
func (*ScanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Token struct {
	AccessToken  string `protobuf:"bytes,1,opt,name=access_token,json=accessToken" json:"access_token,omitempty"`
	TokenType    string `protobuf:"bytes,2,opt,name=token_type,json=tokenType" json:"token_type,omitempty"`
	RefreshToken string `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken" json:"refresh_token,omitempty"`
	Expiry       string `protobuf:"bytes,4,opt,name=expiry" json:"expiry,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Endpoint)(nil), "go.micro.srv.datasource.Endpoint")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.datasource.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.datasource.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.datasource.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.datasource.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.datasource.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.datasource.SearchResponse")
	proto.RegisterType((*ScanRequest)(nil), "go.micro.srv.datasource.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "go.micro.srv.datasource.ScanResponse")
	proto.RegisterType((*Token)(nil), "go.micro.srv.datasource.Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DataSource service

type DataSourceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error)
}

type dataSourceClient struct {
	c           client.Client
	serviceName string
}

func NewDataSourceClient(serviceName string, c client.Client) DataSourceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.datasource"
	}
	return &dataSourceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dataSourceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Scan", in)
	out := new(ScanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataSource service

type DataSourceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Scan(context.Context, *ScanRequest, *ScanResponse) error
}

func RegisterDataSourceHandler(s server.Server, hdlr DataSourceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DataSource{hdlr}, opts...))
}

type DataSource struct {
	DataSourceHandler
}

func (h *DataSource) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.DataSourceHandler.Create(ctx, in, out)
}

func (h *DataSource) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.DataSourceHandler.Delete(ctx, in, out)
}

func (h *DataSource) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.DataSourceHandler.Search(ctx, in, out)
}

func (h *DataSource) Scan(ctx context.Context, in *ScanRequest, out *ScanResponse) error {
	return h.DataSourceHandler.Scan(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/datasource/srv/proto/datasource/datasource.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x25, 0x9f, 0x24, 0x93, 0xc4, 0xaa, 0x56, 0x08, 0xac, 0x48, 0x05, 0x6a, 0x3e, 0x0f, 0xc8,
	0x96, 0x02, 0x47, 0x38, 0x51, 0x4e, 0x48, 0x1c, 0x9c, 0x72, 0xe2, 0x10, 0x39, 0xf6, 0x24, 0xb1,
	0x1a, 0x7b, 0xcd, 0x7a, 0x8d, 0xda, 0xfe, 0x00, 0xfe, 0x13, 0x7f, 0x8d, 0x13, 0xbb, 0x3b, 0xeb,
	0x9a, 0x54, 0x72, 0x7a, 0x9b, 0x79, 0x9e, 0x79, 0x33, 0xf3, 0xf6, 0xc9, 0xf0, 0x75, 0x9b, 0xca,
	0x5d, 0xb5, 0xf6, 0x63, 0x9e, 0x05, 0x97, 0xd1, 0x0d, 0xaf, 0x8a, 0xa0, 0xd8, 0x47, 0x72, 0xc3,
	0x45, 0x16, 0x24, 0x91, 0x8c, 0x4a, 0x5e, 0x89, 0x18, 0x83, 0x52, 0xfc, 0x0a, 0x0a, 0xc1, 0x25,
	0xff, 0x1f, 0x6c, 0x42, 0xdf, 0x7c, 0x63, 0x4f, 0xb6, 0xdc, 0xcf, 0xd2, 0x58, 0x70, 0x5f, 0xd5,
	0xfb, 0xcd, 0x67, 0x6f, 0x0d, 0xa3, 0x2f, 0x79, 0x52, 0xf0, 0x34, 0x97, 0xcc, 0x81, 0x6e, 0x9a,
	0xb8, 0x9d, 0xe7, 0x9d, 0xb7, 0xe3, 0x50, 0x45, 0xec, 0x04, 0x7a, 0x95, 0xd8, 0xbb, 0x5d, 0x03,
	0xe8, 0x90, 0x7d, 0x80, 0x81, 0xe4, 0x97, 0x98, 0xbb, 0x3d, 0x85, 0x4d, 0x16, 0x4f, 0xfd, 0x16,
	0x5a, 0xff, 0x42, 0x57, 0x85, 0x54, 0xec, 0x7d, 0x83, 0xd9, 0x67, 0x81, 0x91, 0xc4, 0x10, 0x7f,
	0x56, 0x58, 0x4a, 0xf6, 0x09, 0x46, 0x68, 0x87, 0x9a, 0x71, 0x93, 0xc5, 0x59, 0x2b, 0x53, 0xbd,
	0x5d, 0x78, 0xdb, 0xe2, 0xbd, 0x03, 0xa7, 0xe6, 0x2b, 0x0b, 0x9e, 0x97, 0xc8, 0xe6, 0x30, 0x12,
	0x36, 0xb6, 0xfb, 0xdf, 0xe6, 0xde, 0x33, 0x98, 0x9d, 0xe3, 0x1e, 0x9b, 0xe9, 0x77, 0xce, 0xf4,
	0x4e, 0xc0, 0xa9, 0x0b, 0x6c, 0xcb, 0x9f, 0x0e, 0xcc, 0x96, 0x18, 0x89, 0x78, 0x57, 0xf7, 0x3c,
	0x82, 0x41, 0x9a, 0x27, 0x78, 0x65, 0xdb, 0x28, 0x61, 0x0c, 0xfa, 0x12, 0x45, 0x66, 0x15, 0x32,
	0xb1, 0xc6, 0x36, 0x82, 0x67, 0x46, 0xa1, 0x5e, 0x68, 0x62, 0x8d, 0x95, 0xe9, 0x0d, 0xba, 0x7d,
	0xc2, 0x74, 0xac, 0x57, 0x8e, 0xd5, 0x09, 0x5b, 0x2e, 0xae, 0xdd, 0x01, 0xad, 0x5c, 0xe7, 0xb5,
	0xf0, 0xc3, 0x46, 0x78, 0x35, 0x3f, 0xc1, 0x42, 0xee, 0xdc, 0x87, 0x86, 0x82, 0x12, 0x33, 0xff,
	0xba, 0x40, 0x77, 0x64, 0xe7, 0xab, 0xd8, 0xfb, 0x08, 0x4e, 0xbd, 0xba, 0x15, 0xe7, 0x31, 0x0c,
	0x95, 0x18, 0xd5, 0x5e, 0xda, 0xe5, 0x6d, 0xa6, 0xbb, 0xd3, 0x7c, 0xc3, 0xeb, 0xed, 0x75, 0xec,
	0x9d, 0xc2, 0x64, 0x19, 0x47, 0x79, 0x9b, 0x54, 0x0e, 0x4c, 0xe9, 0xb3, 0x15, 0xea, 0x77, 0x07,
	0x06, 0xe6, 0xa9, 0xd9, 0x19, 0x4c, 0xa3, 0x38, 0xc6, 0xb2, 0x5c, 0x91, 0x41, 0xa8, 0x67, 0x42,
	0x18, 0x95, 0x9c, 0x02, 0x98, 0x6f, 0x2b, 0xb3, 0x33, 0x4d, 0x1d, 0x1b, 0xe4, 0x42, 0x01, 0xec,
	0x05, 0xcc, 0x04, 0x6e, 0xd4, 0x6e, 0xbb, 0x55, 0xe3, 0xb1, 0x71, 0x38, 0xb5, 0x20, 0x71, 0xa8,
	0x5b, 0xf0, 0xaa, 0x48, 0x95, 0x66, 0x7d, 0xba, 0x85, 0xb2, 0xc5, 0xdf, 0x2e, 0xc0, 0xb9, 0x32,
	0xcd, 0xd2, 0x98, 0x86, 0xfd, 0x80, 0x21, 0x39, 0x84, 0xbd, 0x6e, 0x35, 0xd6, 0x81, 0x25, 0xe7,
	0x6f, 0xee, 0xad, 0xb3, 0x27, 0x3f, 0xd0, 0xe4, 0xe4, 0x97, 0x23, 0xe4, 0x07, 0x8e, 0x3b, 0x42,
	0x7e, 0xc7, 0x78, 0x86, 0x9c, 0x9e, 0xef, 0x08, 0xf9, 0x81, 0x35, 0x8f, 0x90, 0x1f, 0xfa, 0x40,
	0x91, 0x7f, 0x87, 0xbe, 0x7e, 0x3e, 0xf6, 0xb2, 0xbd, 0xa5, 0x79, 0xfc, 0xf9, 0xab, 0x7b, 0xaa,
	0x6a, 0xda, 0xf5, 0xd0, 0xfc, 0x63, 0xde, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xec, 0x4c, 0x4b,
	0xe0, 0xb2, 0x04, 0x00, 0x00,
}
