// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/datasource/srv/proto/datasource/datasource.proto
// DO NOT EDIT!

/*
Package go_micro_srv_datasource is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/datasource/srv/proto/datasource/datasource.proto

It has these top-level messages:
	Endpoint
	CreateRequest
	CreateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
	ScanRequest
	ScanResponse
*/
package go_micro_srv_datasource

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Endpoint struct {
	Id       string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Url      string `protobuf:"bytes,2,opt,name=url" json:"url,omitempty"`
	Size     int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Files    int64  `protobuf:"varint,4,opt,name=files" json:"files,omitempty"`
	LastScan int64  `protobuf:"varint,5,opt,name=last_scan,json=lastScan" json:"last_scan,omitempty"`
}

func (m *Endpoint) Reset()                    { *m = Endpoint{} }
func (m *Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Endpoint) ProtoMessage()               {}
func (*Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateRequest struct {
	Endpoint *Endpoint `protobuf:"bytes,1,opt,name=endpoint" json:"endpoint,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetEndpoint() *Endpoint {
	if m != nil {
		return m.Endpoint
	}
	return nil
}

type CreateResponse struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type SearchRequest struct {
	Query  string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Limit  int64  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Offset int64  `protobuf:"varint,3,opt,name=offset" json:"offset,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type SearchResponse struct {
	Result []*Endpoint `protobuf:"bytes,1,rep,name=result" json:"result,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchResponse) GetResult() []*Endpoint {
	if m != nil {
		return m.Result
	}
	return nil
}

type ScanRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ScanRequest) Reset()                    { *m = ScanRequest{} }
func (m *ScanRequest) String() string            { return proto.CompactTextString(m) }
func (*ScanRequest) ProtoMessage()               {}
func (*ScanRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type ScanResponse struct {
}

func (m *ScanResponse) Reset()                    { *m = ScanResponse{} }
func (m *ScanResponse) String() string            { return proto.CompactTextString(m) }
func (*ScanResponse) ProtoMessage()               {}
func (*ScanResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func init() {
	proto.RegisterType((*Endpoint)(nil), "go.micro.srv.datasource.Endpoint")
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.datasource.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.datasource.CreateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "go.micro.srv.datasource.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "go.micro.srv.datasource.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.srv.datasource.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.srv.datasource.SearchResponse")
	proto.RegisterType((*ScanRequest)(nil), "go.micro.srv.datasource.ScanRequest")
	proto.RegisterType((*ScanResponse)(nil), "go.micro.srv.datasource.ScanResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DataSource service

type DataSourceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error)
}

type dataSourceClient struct {
	c           client.Client
	serviceName string
}

func NewDataSourceClient(serviceName string, c client.Client) DataSourceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.datasource"
	}
	return &dataSourceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dataSourceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourceClient) Scan(ctx context.Context, in *ScanRequest, opts ...client.CallOption) (*ScanResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DataSource.Scan", in)
	out := new(ScanResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DataSource service

type DataSourceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Scan(context.Context, *ScanRequest, *ScanResponse) error
}

func RegisterDataSourceHandler(s server.Server, hdlr DataSourceHandler) {
	s.Handle(s.NewHandler(&DataSource{hdlr}))
}

type DataSource struct {
	DataSourceHandler
}

func (h *DataSource) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.DataSourceHandler.Create(ctx, in, out)
}

func (h *DataSource) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.DataSourceHandler.Delete(ctx, in, out)
}

func (h *DataSource) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.DataSourceHandler.Search(ctx, in, out)
}

func (h *DataSource) Scan(ctx context.Context, in *ScanRequest, out *ScanResponse) error {
	return h.DataSourceHandler.Scan(ctx, in, out)
}

var fileDescriptor0 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x93, 0xcf, 0xaf, 0x93, 0x40,
	0x10, 0xc7, 0x7d, 0xa5, 0x25, 0x74, 0x6a, 0x49, 0xb3, 0x31, 0x4a, 0x6a, 0x8c, 0x4a, 0xfc, 0x75,
	0x30, 0x90, 0xd4, 0x93, 0x07, 0x4f, 0xd6, 0x53, 0x13, 0x0f, 0x10, 0x4f, 0x1e, 0xcc, 0x96, 0x2e,
	0xed, 0x46, 0x60, 0x71, 0x77, 0x31, 0xb1, 0x7f, 0xba, 0x27, 0x97, 0x65, 0x29, 0xd2, 0x04, 0xfa,
	0x6e, 0x33, 0xb3, 0x33, 0xdf, 0x99, 0xf9, 0x4c, 0x16, 0x76, 0x47, 0x2a, 0x4f, 0xd5, 0x3e, 0x48,
	0x58, 0x1e, 0xfe, 0xc4, 0x67, 0x56, 0x95, 0x61, 0x99, 0x61, 0x99, 0x32, 0x9e, 0x87, 0x07, 0x2c,
	0xb1, 0x60, 0x15, 0x4f, 0x48, 0x28, 0xf8, 0xef, 0xb0, 0xe4, 0x4c, 0xb2, 0xff, 0x83, 0x9d, 0x19,
	0xe8, 0x37, 0xf4, 0xe4, 0xc8, 0x82, 0x9c, 0x26, 0x9c, 0x05, 0x2a, 0x3f, 0xe8, 0x9e, 0x7d, 0x01,
	0xce, 0x97, 0xe2, 0x50, 0x32, 0x5a, 0x48, 0xe4, 0xc2, 0x84, 0x1e, 0xbc, 0xbb, 0x17, 0x77, 0xef,
	0xe6, 0x91, 0xb2, 0xd0, 0x0a, 0xac, 0x8a, 0x67, 0xde, 0x44, 0x07, 0x6a, 0x13, 0x21, 0x98, 0x0a,
	0x7a, 0x26, 0x9e, 0xa5, 0x42, 0x56, 0xa4, 0x6d, 0xf4, 0x08, 0x66, 0x29, 0xcd, 0x88, 0xf0, 0xa6,
	0x3a, 0xd8, 0x38, 0xe8, 0x29, 0xcc, 0x33, 0x2c, 0xe4, 0x0f, 0x91, 0xe0, 0xc2, 0x9b, 0xe9, 0x17,
	0xa7, 0x0e, 0xc4, 0xca, 0xf7, 0xbf, 0xc2, 0xf2, 0x33, 0x27, 0x58, 0x92, 0x88, 0xfc, 0xaa, 0x88,
	0x90, 0xe8, 0x13, 0x38, 0xc4, 0x4c, 0xa1, 0xfb, 0x2f, 0x36, 0x2f, 0x83, 0x81, 0x89, 0x83, 0x76,
	0xdc, 0xe8, 0x52, 0xe2, 0xbf, 0x07, 0xb7, 0xd5, 0x13, 0x25, 0x2b, 0x04, 0x41, 0x6b, 0x70, 0xb8,
	0xb1, 0xcd, 0x42, 0x17, 0xdf, 0x7f, 0x0e, 0xcb, 0x2d, 0xc9, 0x48, 0xd7, 0xfd, 0x6a, 0x6f, 0x7f,
	0x05, 0x6e, 0x9b, 0x60, 0x4a, 0x62, 0x58, 0xc6, 0x04, 0xf3, 0xe4, 0xd4, 0x96, 0xa8, 0xa5, 0x95,
	0xc1, 0xff, 0x98, 0xaa, 0xc6, 0xa9, 0xa3, 0x19, 0xcd, 0xa9, 0xd4, 0xc8, 0x14, 0x0a, 0xed, 0xa0,
	0xc7, 0x60, 0xb3, 0x34, 0x15, 0x44, 0x1a, 0x6c, 0xc6, 0xf3, 0x77, 0xe0, 0xb6, 0xa2, 0x66, 0xea,
	0x8f, 0x60, 0xab, 0x29, 0xab, 0xac, 0x86, 0x60, 0xdd, 0x0f, 0x82, 0x29, 0xf0, 0x9f, 0xc1, 0xa2,
	0x46, 0x3b, 0xb4, 0x92, 0x0b, 0x0f, 0x9b, 0xe7, 0xa6, 0xd3, 0xe6, 0xef, 0x04, 0x60, 0xab, 0xe4,
	0x62, 0x2d, 0x87, 0xbe, 0x83, 0xdd, 0x00, 0x44, 0x6f, 0x06, 0x5b, 0xf6, 0x2e, 0xb6, 0x7e, 0x7b,
	0x33, 0xcf, 0xa0, 0x7b, 0x50, 0x8b, 0x37, 0x38, 0x47, 0xc4, 0x7b, 0x07, 0x19, 0x11, 0xbf, 0xba,
	0x8b, 0x16, 0x6f, 0x20, 0x8e, 0x88, 0xf7, 0x4e, 0x37, 0x22, 0xde, 0xbf, 0x86, 0x12, 0xff, 0x06,
	0xd3, 0x9a, 0x1a, 0x7a, 0x35, 0x5c, 0xd2, 0x31, 0x5f, 0xbf, 0xbe, 0x91, 0xd5, 0xca, 0xee, 0x6d,
	0xfd, 0x27, 0x3f, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x06, 0x21, 0x9e, 0xb9, 0xe2, 0x03, 0x00,
	0x00,
}
