config-srv:
  command: --registry_address=registry:8500
  image: kazoup/config-srv
  links:
  - registry

config-api:
  command: --registry_address=registry:8500
  image: kazoup/config-api
  links:
  - registry
