registry:
  hostname: registry
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

elasticsearch:
 image: elasticsearch:1.7
 hostname: "elasticsearch"
 ports:
   - "9200:9200"
   - "9300:9300"
 environment:
   ES_HEAP_SIZE: 512m
   ES_CLUSTER_NAME: Kazoup

api:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 --api_cors=* --enable_stats api
  image: microhq/micro
  links:
  - registry
  ports:
  - "8080:8080"

web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  image: microhq/micro
  links:
  - registry
  ports:
  - "8082:8082"

config-srv:
  command: --registry_address=registry:8500
  build: srv
  links:
  - registry

config-api:
  command: --registry_address=registry:8500
  build: api
  links:
  - registry

flag-srv:
  command: --registry_address=registry:8500
  image : kazoup/flag-srv
  links:
  - registry

flag-api:
  command: --registry_address=registry:8500
  image : kazoup/flag-api
  links:
  - registry

elastic-api:
  command: --registry_address=registry:8500
  image : kazoup/elastic-api
  links:
  - registry

elastic-srv:
  command: --registry_address=registry:8500 --elasticsearch_hosts=elasticsearch:9200
  image: kazoup/elastic-srv
  links:
  - elasticsearch
  - registry
