apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: audio-srv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: audio-srv
    spec:
      containers:
      - name: audio-srv
        command: [
                  "/srv",
                  "--registry=kubernetes",
                  "--server_address=0.0.0.0:9090",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--transport=tcp",
                  ]
        image: eu.gcr.io/desktop-1470249894548/audio-srv:latest
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value:  "/google-cloud-service-account/google-cloud-service-account.json"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: audio-port
        - containerPort: 10001
          name: broker-port
        volumeMounts:
        - name: google-cloud-service-account
          mountPath: "/google-cloud-service-account"
          readOnly: true
        - name: aws-credentials
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: google-cloud-service-account
        secret:
          secretName: "google-cloud-service-account"
      - name: aws-credentials
        secret:
          secretName: "aws-credentials"
