apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config-srv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: config-srv
    spec:
      containers:
      - name: config-srv
        command: [
                  "/srv",
                  "--registry=kubernetes",           
                  "--server_address=0.0.0.0:9090",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--selector=cache",
                  ]
        image: eu.gcr.io/desktop-1470249894548/config-srv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: config-port
        - containerPort: 10001
          name: broker-port
