apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crawler-srv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: crawler-srv
    spec:
      containers:
      - name: crawler-srv
        command: [
                  "/srv",
                  "--registry=kubernetes",            
                  "--server_address=0.0.0.0:9090",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--transport=tcp",
                  ]
        image: eu.gcr.io/desktop-1470249894548/crawler-srv:latest
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value:  "/google-cloud-service-account/google-cloud-service-account.json"
          - name: ELASTICSEARCH_URL
            value:  "https://8d22518314b8a6bab84906817730e7f4.eu-west-1.aws.found.io:9243"
          - name: ES_USERNAME
            value: "admin"
          - name: ES_PASSWORD
            value: "9svne8f655h"
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: crawler-port
        - containerPort: 10001
          name: broker-port
        volumeMounts: 
        - name: google-cloud-service-account
          mountPath: "/google-cloud-service-account"
          readOnly: true
        - name: aws-credentials
          mountPath: "/root/.aws"
          readOnly: true
      volumes:
      - name: google-cloud-service-account
        secret: 
          secretName: "google-cloud-service-account"
      - name: aws-credentials
        secret: 
          secretName: "aws-credentials"
