apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: search-srv
spec:
  replicas: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: search-srv
    spec:
      containers:
      - name: search-srv
        command: [
                  "/srv",
                  "--registry=consul",
                  "--registry_address=$(REGISTRY_SERVICE_HOST)", 
                  "--server_address=0.0.0.0:9090",
                  "--broker=nats",
                  "--broker_address=nats:4222",
                  "--transport=tcp",
                  ]
        image: eu.gcr.io/desktop-1470249894548/search-srv:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
          name: search-port
        - containerPort: 10001
          name: broker-port
        volumeMounts: 
        - name: google-cloud-service-account
          mountPath: "/google-cloud-service-account"
          readOnly: true
        - name: aws-credentials
          mountPath: "/root/.aws/credentials"
          readOnly: true
      volumes:
      - name: google-cloud-service-account
        secret: 
          secretName: "google-cloud-service-account"
      - name: aws-credentials
        secret: 
          secretName: "aws-credentials"