apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    component: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
          name: redis
