// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/file/srv/proto/file/file.proto
// DO NOT EDIT!

/*
Package go_micro_srv_file is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/file/srv/proto/file/file.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
*/
package go_micro_srv_file

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	DatasourceId string `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId" json:"datasource_id,omitempty"`
	MimeType     string `protobuf:"bytes,2,opt,name=mime_type,json=mimeType" json:"mime_type,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateResponse struct {
	DocUrl string `protobuf:"bytes,1,opt,name=doc_url,json=docUrl" json:"doc_url,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.file.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.file.CreateResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for File service

type FileClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
}

type fileClient struct {
	c           client.Client
	serviceName string
}

func NewFileClient(serviceName string, c client.Client) FileClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.file"
	}
	return &fileClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *fileClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "File.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for File service

type FileHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
}

func RegisterFileHandler(s server.Server, hdlr FileHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&File{hdlr}, opts...))
}

type File struct {
	FileHandler
}

func (h *File) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.FileHandler.Create(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/file/srv/proto/file/file.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xb2, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xac, 0xca, 0x2f, 0x2d, 0xd0, 0x2f, 0xc8,
	0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x4f, 0xcb, 0xcc, 0x49, 0xd5, 0x2f, 0x2e, 0x2a, 0xd3,
	0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0x70, 0x41, 0x84, 0x1e, 0x98, 0x2f, 0x24, 0x98, 0x9e, 0xaf,
	0x97, 0x9b, 0x99, 0x5c, 0x94, 0xaf, 0x07, 0x54, 0xa3, 0x07, 0x92, 0x50, 0x0a, 0xe4, 0xe2, 0x75,
	0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe6, 0xe2,
	0x4d, 0x49, 0x2c, 0x49, 0x2c, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0x8d, 0xcf, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x41, 0x08, 0x7a, 0xa6, 0x08, 0x49, 0x73, 0x71, 0xe6, 0x66, 0xe6,
	0xa6, 0xc6, 0x97, 0x54, 0x16, 0xa4, 0x4a, 0x30, 0x81, 0x15, 0x70, 0x80, 0x04, 0x42, 0x80, 0x7c,
	0x25, 0x4d, 0x2e, 0x3e, 0x98, 0x91, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0xe2, 0x5c, 0xec,
	0x29, 0xf9, 0xc9, 0xf1, 0xa5, 0x45, 0x39, 0x50, 0xd3, 0xd8, 0x80, 0xdc, 0xd0, 0xa2, 0x1c, 0xa3,
	0x70, 0x2e, 0x16, 0x37, 0xa0, 0x2b, 0x84, 0xfc, 0xb9, 0xd8, 0x20, 0x5a, 0x84, 0x14, 0xf4, 0x30,
	0xdc, 0xa8, 0x87, 0xe2, 0x40, 0x29, 0x45, 0x3c, 0x2a, 0x20, 0xf6, 0x29, 0x31, 0x24, 0xb1, 0x81,
	0x3d, 0x6c, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xb8, 0x52, 0x5f, 0x2d, 0x01, 0x00, 0x00,
}
