// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/db/srv/proto/config/config.proto
// DO NOT EDIT!

/*
Package go_micro_srv_db is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/db/srv/proto/config/config.proto
	github.com/kazoup/platform/db/srv/proto/db/db.proto

It has these top-level messages:
	DocRef
	BulkCreateRequest
	BulkCreateResponse
	CreateIndexRequest
	CreateIndexResponse
	StatusRequest
	StatusResponse
	AddAliasRequest
	AddAliasResponse
	DeleteIndexRequest
	DeleteIndexResponse
	DeleteAliasRequest
	DeleteAliasResponse
	RenameAliasRequest
	RenameAliasResponse
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	DeleteByQueryRequest
	DeleteByQueryResponse
	SearchRequest
	SearchResponse
	SearchByIdRequest
	SearchByIdResponse
*/
package go_micro_srv_db

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DocRef struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *DocRef) Reset()                    { *m = DocRef{} }
func (m *DocRef) String() string            { return proto.CompactTextString(m) }
func (*DocRef) ProtoMessage()               {}
func (*DocRef) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BulkCreateRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type" json:"type,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
	Data  string `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *BulkCreateRequest) Reset()                    { *m = BulkCreateRequest{} }
func (m *BulkCreateRequest) String() string            { return proto.CompactTextString(m) }
func (*BulkCreateRequest) ProtoMessage()               {}
func (*BulkCreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type BulkCreateResponse struct {
}

func (m *BulkCreateResponse) Reset()                    { *m = BulkCreateResponse{} }
func (m *BulkCreateResponse) String() string            { return proto.CompactTextString(m) }
func (*BulkCreateResponse) ProtoMessage()               {}
func (*BulkCreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CreateIndexRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
}

func (m *CreateIndexRequest) Reset()                    { *m = CreateIndexRequest{} }
func (m *CreateIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateIndexRequest) ProtoMessage()               {}
func (*CreateIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateIndexResponse struct {
}

func (m *CreateIndexResponse) Reset()                    { *m = CreateIndexResponse{} }
func (m *CreateIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateIndexResponse) ProtoMessage()               {}
func (*CreateIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type StatusRequest struct {
}

func (m *StatusRequest) Reset()                    { *m = StatusRequest{} }
func (m *StatusRequest) String() string            { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()               {}
func (*StatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type StatusResponse struct {
	Status string `protobuf:"bytes,1,opt,name=status" json:"status,omitempty"`
}

func (m *StatusResponse) Reset()                    { *m = StatusResponse{} }
func (m *StatusResponse) String() string            { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()               {}
func (*StatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type AddAliasRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Alias string `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
}

func (m *AddAliasRequest) Reset()                    { *m = AddAliasRequest{} }
func (m *AddAliasRequest) String() string            { return proto.CompactTextString(m) }
func (*AddAliasRequest) ProtoMessage()               {}
func (*AddAliasRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type AddAliasResponse struct {
}

func (m *AddAliasResponse) Reset()                    { *m = AddAliasResponse{} }
func (m *AddAliasResponse) String() string            { return proto.CompactTextString(m) }
func (*AddAliasResponse) ProtoMessage()               {}
func (*AddAliasResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteIndexRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
}

func (m *DeleteIndexRequest) Reset()                    { *m = DeleteIndexRequest{} }
func (m *DeleteIndexRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexRequest) ProtoMessage()               {}
func (*DeleteIndexRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type DeleteIndexResponse struct {
}

func (m *DeleteIndexResponse) Reset()                    { *m = DeleteIndexResponse{} }
func (m *DeleteIndexResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteIndexResponse) ProtoMessage()               {}
func (*DeleteIndexResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type DeleteAliasRequest struct {
	Index string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	Alias string `protobuf:"bytes,2,opt,name=alias" json:"alias,omitempty"`
}

func (m *DeleteAliasRequest) Reset()                    { *m = DeleteAliasRequest{} }
func (m *DeleteAliasRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteAliasRequest) ProtoMessage()               {}
func (*DeleteAliasRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

type DeleteAliasResponse struct {
}

func (m *DeleteAliasResponse) Reset()                    { *m = DeleteAliasResponse{} }
func (m *DeleteAliasResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteAliasResponse) ProtoMessage()               {}
func (*DeleteAliasResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

type RenameAliasRequest struct {
	Index    string `protobuf:"bytes,1,opt,name=index" json:"index,omitempty"`
	OldAlias string `protobuf:"bytes,2,opt,name=old_alias,json=oldAlias" json:"old_alias,omitempty"`
	NewAlias string `protobuf:"bytes,3,opt,name=new_alias,json=newAlias" json:"new_alias,omitempty"`
}

func (m *RenameAliasRequest) Reset()                    { *m = RenameAliasRequest{} }
func (m *RenameAliasRequest) String() string            { return proto.CompactTextString(m) }
func (*RenameAliasRequest) ProtoMessage()               {}
func (*RenameAliasRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type RenameAliasResponse struct {
}

func (m *RenameAliasResponse) Reset()                    { *m = RenameAliasResponse{} }
func (m *RenameAliasResponse) String() string            { return proto.CompactTextString(m) }
func (*RenameAliasResponse) ProtoMessage()               {}
func (*RenameAliasResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func init() {
	proto.RegisterType((*DocRef)(nil), "go.micro.srv.db.DocRef")
	proto.RegisterType((*BulkCreateRequest)(nil), "go.micro.srv.db.BulkCreateRequest")
	proto.RegisterType((*BulkCreateResponse)(nil), "go.micro.srv.db.BulkCreateResponse")
	proto.RegisterType((*CreateIndexRequest)(nil), "go.micro.srv.db.CreateIndexRequest")
	proto.RegisterType((*CreateIndexResponse)(nil), "go.micro.srv.db.CreateIndexResponse")
	proto.RegisterType((*StatusRequest)(nil), "go.micro.srv.db.StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "go.micro.srv.db.StatusResponse")
	proto.RegisterType((*AddAliasRequest)(nil), "go.micro.srv.db.AddAliasRequest")
	proto.RegisterType((*AddAliasResponse)(nil), "go.micro.srv.db.AddAliasResponse")
	proto.RegisterType((*DeleteIndexRequest)(nil), "go.micro.srv.db.DeleteIndexRequest")
	proto.RegisterType((*DeleteIndexResponse)(nil), "go.micro.srv.db.DeleteIndexResponse")
	proto.RegisterType((*DeleteAliasRequest)(nil), "go.micro.srv.db.DeleteAliasRequest")
	proto.RegisterType((*DeleteAliasResponse)(nil), "go.micro.srv.db.DeleteAliasResponse")
	proto.RegisterType((*RenameAliasRequest)(nil), "go.micro.srv.db.RenameAliasRequest")
	proto.RegisterType((*RenameAliasResponse)(nil), "go.micro.srv.db.RenameAliasResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Config service

type ConfigClient interface {
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...client.CallOption) (*CreateIndexResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error)
	AddAlias(ctx context.Context, in *AddAliasRequest, opts ...client.CallOption) (*AddAliasResponse, error)
	DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...client.CallOption) (*DeleteIndexResponse, error)
	DeleteAlias(ctx context.Context, in *DeleteAliasRequest, opts ...client.CallOption) (*DeleteAliasResponse, error)
	RenameAlias(ctx context.Context, in *RenameAliasRequest, opts ...client.CallOption) (*RenameAliasResponse, error)
}

type configClient struct {
	c           client.Client
	serviceName string
}

func NewConfigClient(serviceName string, c client.Client) ConfigClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.db"
	}
	return &configClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *configClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...client.CallOption) (*CreateIndexResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.CreateIndex", in)
	out := new(CreateIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) Status(ctx context.Context, in *StatusRequest, opts ...client.CallOption) (*StatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.Status", in)
	out := new(StatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) AddAlias(ctx context.Context, in *AddAliasRequest, opts ...client.CallOption) (*AddAliasResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.AddAlias", in)
	out := new(AddAliasResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, opts ...client.CallOption) (*DeleteIndexResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.DeleteIndex", in)
	out := new(DeleteIndexResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) DeleteAlias(ctx context.Context, in *DeleteAliasRequest, opts ...client.CallOption) (*DeleteAliasResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.DeleteAlias", in)
	out := new(DeleteAliasResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *configClient) RenameAlias(ctx context.Context, in *RenameAliasRequest, opts ...client.CallOption) (*RenameAliasResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Config.RenameAlias", in)
	out := new(RenameAliasResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Config service

type ConfigHandler interface {
	CreateIndex(context.Context, *CreateIndexRequest, *CreateIndexResponse) error
	Status(context.Context, *StatusRequest, *StatusResponse) error
	AddAlias(context.Context, *AddAliasRequest, *AddAliasResponse) error
	DeleteIndex(context.Context, *DeleteIndexRequest, *DeleteIndexResponse) error
	DeleteAlias(context.Context, *DeleteAliasRequest, *DeleteAliasResponse) error
	RenameAlias(context.Context, *RenameAliasRequest, *RenameAliasResponse) error
}

func RegisterConfigHandler(s server.Server, hdlr ConfigHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Config{hdlr}, opts...))
}

type Config struct {
	ConfigHandler
}

func (h *Config) CreateIndex(ctx context.Context, in *CreateIndexRequest, out *CreateIndexResponse) error {
	return h.ConfigHandler.CreateIndex(ctx, in, out)
}

func (h *Config) Status(ctx context.Context, in *StatusRequest, out *StatusResponse) error {
	return h.ConfigHandler.Status(ctx, in, out)
}

func (h *Config) AddAlias(ctx context.Context, in *AddAliasRequest, out *AddAliasResponse) error {
	return h.ConfigHandler.AddAlias(ctx, in, out)
}

func (h *Config) DeleteIndex(ctx context.Context, in *DeleteIndexRequest, out *DeleteIndexResponse) error {
	return h.ConfigHandler.DeleteIndex(ctx, in, out)
}

func (h *Config) DeleteAlias(ctx context.Context, in *DeleteAliasRequest, out *DeleteAliasResponse) error {
	return h.ConfigHandler.DeleteAlias(ctx, in, out)
}

func (h *Config) RenameAlias(ctx context.Context, in *RenameAliasRequest, out *RenameAliasResponse) error {
	return h.ConfigHandler.RenameAlias(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/db/srv/proto/config/config.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 437 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0x5f, 0xcf, 0x93, 0x30,
	0x14, 0xc6, 0xdf, 0x77, 0x4e, 0xb2, 0x1d, 0xe3, 0xa6, 0x75, 0x1a, 0x32, 0x13, 0x9d, 0x75, 0x17,
	0x8b, 0x17, 0x90, 0xe8, 0xa5, 0x31, 0x71, 0x7f, 0x6e, 0x8c, 0x57, 0xe2, 0x9d, 0x37, 0xa6, 0xd0,
	0x6e, 0x92, 0x01, 0x45, 0x28, 0xfe, 0xfb, 0x24, 0x7e, 0xdc, 0x17, 0xda, 0xb2, 0xc1, 0x60, 0x64,
	0xd9, 0x15, 0xed, 0xd3, 0xa7, 0xbf, 0xd3, 0x93, 0xf3, 0x04, 0x78, 0xbf, 0xf3, 0xc5, 0x8f, 0xcc,
	0xb5, 0x3c, 0x1e, 0xda, 0x7b, 0xf2, 0x8f, 0x67, 0xb1, 0x1d, 0x07, 0x44, 0x6c, 0x79, 0x12, 0xda,
	0xd4, 0xb5, 0xd3, 0xe4, 0x97, 0x1d, 0x27, 0x5c, 0x70, 0xdb, 0xe3, 0xd1, 0xd6, 0xdf, 0xe9, 0x8f,
	0x25, 0x35, 0x34, 0xde, 0x71, 0x2b, 0xf4, 0xbd, 0x84, 0x5b, 0xb9, 0xcf, 0xa2, 0x2e, 0x5e, 0x81,
	0xb1, 0xe1, 0x9e, 0xc3, 0xb6, 0x68, 0x02, 0xf7, 0xfd, 0x88, 0xb2, 0x3f, 0xe6, 0xed, 0xec, 0x76,
	0x31, 0x74, 0xd4, 0x06, 0x21, 0xe8, 0x8b, 0xbf, 0x31, 0x33, 0x7b, 0x52, 0x94, 0x6b, 0x34, 0x82,
	0x9e, 0x4f, 0xcd, 0x7b, 0x52, 0xc9, 0x57, 0x98, 0xc0, 0xe3, 0x55, 0x16, 0xec, 0xd7, 0x09, 0x23,
	0x82, 0x39, 0xec, 0x67, 0xc6, 0x52, 0x71, 0x3d, 0xae, 0xf0, 0x50, 0x22, 0x88, 0xd9, 0x57, 0x9e,
	0x62, 0x8d, 0x27, 0x80, 0xaa, 0x25, 0xd2, 0x98, 0x47, 0x29, 0xc3, 0x6f, 0x00, 0x29, 0xe5, 0x53,
	0x01, 0xef, 0xac, 0x8c, 0x9f, 0xc2, 0x93, 0x9a, 0x57, 0x23, 0xc6, 0xf0, 0xf0, 0xab, 0x20, 0x22,
	0x4b, 0xf5, 0x6d, 0xbc, 0x80, 0x51, 0x29, 0x28, 0x0b, 0x7a, 0x06, 0x46, 0x2a, 0x15, 0x0d, 0xd4,
	0x3b, 0xfc, 0x01, 0xc6, 0x4b, 0x4a, 0x97, 0x81, 0x4f, 0xd2, 0xee, 0xa6, 0x73, 0x95, 0x14, 0x2e,
	0xdd, 0xb5, 0xda, 0x60, 0x04, 0x8f, 0x8e, 0xd7, 0x8f, 0x0d, 0x6d, 0x58, 0xc0, 0x2e, 0x6d, 0xa8,
	0xe6, 0xd5, 0x88, 0x8f, 0x25, 0xe2, 0xea, 0x87, 0x1d, 0xc0, 0xf5, 0xb7, 0x51, 0x40, 0x0e, 0x8b,
	0x48, 0x78, 0x09, 0xf8, 0x39, 0x0c, 0x79, 0x40, 0xbf, 0x57, 0xe1, 0x83, 0x5c, 0x90, 0x37, 0x8b,
	0xc3, 0x88, 0xfd, 0xd6, 0x87, 0x6a, 0xec, 0x83, 0x5c, 0x58, 0x96, 0xc5, 0x6b, 0x55, 0x54, 0xf1,
	0xb7, 0xff, 0xfb, 0x60, 0xac, 0x65, 0x90, 0xd1, 0x37, 0x78, 0x50, 0x19, 0x24, 0x7a, 0x6d, 0x9d,
	0x44, 0xda, 0x6a, 0x46, 0x62, 0x3a, 0xef, 0x36, 0xe9, 0x0e, 0x6f, 0xd0, 0x67, 0x30, 0xd4, 0xf0,
	0xd1, 0x8b, 0xc6, 0x8d, 0x5a, 0x4c, 0xa6, 0x2f, 0xcf, 0x9e, 0x1f, 0x60, 0x5f, 0x60, 0x50, 0x0e,
	0x18, 0xcd, 0x1a, 0xf6, 0x93, 0xe8, 0x4c, 0x5f, 0x75, 0x38, 0x0e, 0xc8, 0xbc, 0xf7, 0xca, 0xcc,
	0x5b, 0x7a, 0x6f, 0xa6, 0xa7, 0xa5, 0xf7, 0xb6, 0xd8, 0x54, 0xd8, 0xea, 0xc5, 0xe7, 0xd8, 0xb5,
	0x47, 0xcf, 0xbb, 0x4d, 0x55, 0x76, 0x65, 0xaa, 0x2d, 0xec, 0x66, 0xb2, 0x5a, 0xd8, 0x2d, 0xc1,
	0xc0, 0x37, 0xae, 0x21, 0xff, 0x6c, 0xef, 0xee, 0x02, 0x00, 0x00, 0xff, 0xff, 0xce, 0xae, 0x0e,
	0x01, 0x18, 0x05, 0x00, 0x00,
}
