// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/kazoup/platform/agent/srv/proto/agent/agent.proto

/*
Package proto_agent is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/agent/srv/proto/agent/agent.proto

It has these top-level messages:
	SaveRequest
	SaveResponse
*/
package proto_agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SaveRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *SaveRequest) Reset()                    { *m = SaveRequest{} }
func (m *SaveRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()               {}
func (*SaveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SaveRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type SaveResponse struct {
	Info string `protobuf:"bytes,1,opt,name=info" json:"info,omitempty"`
}

func (m *SaveResponse) Reset()                    { *m = SaveResponse{} }
func (m *SaveResponse) String() string            { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()               {}
func (*SaveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SaveResponse) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveRequest)(nil), "proto.agent.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "proto.agent.SaveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Service service

type ServiceClient interface {
	Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error)
}

type serviceClient struct {
	c           client.Client
	serviceName string
}

func NewServiceClient(serviceName string, c client.Client) ServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "proto.agent"
	}
	return &serviceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *serviceClient) Save(ctx context.Context, in *SaveRequest, opts ...client.CallOption) (*SaveResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Service.Save", in)
	out := new(SaveResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceHandler interface {
	Save(context.Context, *SaveRequest, *SaveResponse) error
}

func RegisterServiceHandler(s server.Server, hdlr ServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Service{hdlr}, opts...))
}

type Service struct {
	ServiceHandler
}

func (h *Service) Save(ctx context.Context, in *SaveRequest, out *SaveResponse) error {
	return h.ServiceHandler.Save(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/agent/srv/proto/agent/agent.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x49, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4e, 0xac, 0xca, 0x2f, 0x2d, 0xd0, 0x2f, 0xc8,
	0x49, 0x2c, 0x49, 0xcb, 0x2f, 0xca, 0xd5, 0x4f, 0x4c, 0x4f, 0xcd, 0x2b, 0xd1, 0x2f, 0x2e, 0x2a,
	0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x87, 0xf2, 0xc1, 0xa4, 0x1e, 0x58, 0x44, 0x88, 0x1b, 0x4c,
	0xe9, 0x81, 0x85, 0x94, 0x14, 0xb9, 0xb8, 0x83, 0x13, 0xcb, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53,
	0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xc0, 0x6c, 0x25, 0x25, 0x2e, 0x1e, 0x88, 0x92, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x90,
	0x9a, 0xcc, 0xbc, 0xb4, 0x7c, 0x98, 0x1a, 0x10, 0xdb, 0xc8, 0x83, 0x8b, 0x3d, 0x38, 0xb5, 0xa8,
	0x2c, 0x33, 0x39, 0x55, 0xc8, 0x96, 0x8b, 0x05, 0xa4, 0x5c, 0x48, 0x42, 0x0f, 0xc9, 0x1e, 0x3d,
	0x24, 0x4b, 0xa4, 0x24, 0xb1, 0xc8, 0x40, 0xcc, 0x56, 0x62, 0x48, 0x62, 0x03, 0xcb, 0x19, 0x03,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x42, 0xa2, 0xce, 0xe4, 0x00, 0x00, 0x00,
}
