// Code generated by protoc-gen-go.
// source: github.com/kazoup/platform/docenrich/srv/proto/docenrich/docenrich.proto
// DO NOT EDIT!

/*
Package go_micro_srv_docenrich is a generated protocol buffer package.

It is generated from these files:
	github.com/kazoup/platform/docenrich/srv/proto/docenrich/docenrich.proto

It has these top-level messages:
	CreateRequest
	CreateResponse
	HealthRequest
	HealthResponse
*/
package go_micro_srv_docenrich

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateRequest struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Index string `protobuf:"bytes,2,opt,name=index" json:"index,omitempty"`
	Id    string `protobuf:"bytes,3,opt,name=id" json:"id,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CreateResponse struct {
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type HealthRequest struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
}

func (m *HealthRequest) Reset()                    { *m = HealthRequest{} }
func (m *HealthRequest) String() string            { return proto.CompactTextString(m) }
func (*HealthRequest) ProtoMessage()               {}
func (*HealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type HealthResponse struct {
	Status int64  `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
	Info   string `protobuf:"bytes,2,opt,name=info" json:"info,omitempty"`
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*CreateRequest)(nil), "go.micro.srv.docenrich.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "go.micro.srv.docenrich.CreateResponse")
	proto.RegisterType((*HealthRequest)(nil), "go.micro.srv.docenrich.HealthRequest")
	proto.RegisterType((*HealthResponse)(nil), "go.micro.srv.docenrich.HealthResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DocEnrich service

type DocEnrichClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error)
}

type docEnrichClient struct {
	c           client.Client
	serviceName string
}

func NewDocEnrichClient(serviceName string, c client.Client) DocEnrichClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "go.micro.srv.docenrich"
	}
	return &docEnrichClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *docEnrichClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DocEnrich.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *docEnrichClient) Health(ctx context.Context, in *HealthRequest, opts ...client.CallOption) (*HealthResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DocEnrich.Health", in)
	out := new(HealthResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DocEnrich service

type DocEnrichHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Health(context.Context, *HealthRequest, *HealthResponse) error
}

func RegisterDocEnrichHandler(s server.Server, hdlr DocEnrichHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DocEnrich{hdlr}, opts...))
}

type DocEnrich struct {
	DocEnrichHandler
}

func (h *DocEnrich) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.DocEnrichHandler.Create(ctx, in, out)
}

func (h *DocEnrich) Health(ctx context.Context, in *HealthRequest, out *HealthResponse) error {
	return h.DocEnrichHandler.Health(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/kazoup/platform/docenrich/srv/proto/docenrich/docenrich.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0x03, 0x31,
	0x10, 0xc5, 0xfb, 0x47, 0x17, 0x3a, 0xd0, 0x45, 0x82, 0x94, 0xc5, 0x93, 0x44, 0x14, 0x4f, 0x09,
	0xe8, 0xd5, 0x9b, 0x0a, 0xf5, 0xba, 0x37, 0x8f, 0x69, 0x36, 0xed, 0x06, 0xbb, 0x3b, 0x31, 0x99,
	0x15, 0xf5, 0xdb, 0xf9, 0xcd, 0x6c, 0xb3, 0xdb, 0xe2, 0x82, 0xd5, 0xdb, 0xcb, 0xcc, 0x9b, 0xc7,
	0xfb, 0x11, 0x98, 0xaf, 0x2c, 0x95, 0xcd, 0x42, 0x68, 0xac, 0xe4, 0x8b, 0xfa, 0xc4, 0xc6, 0x49,
	0xb7, 0x56, 0xb4, 0x44, 0x5f, 0xc9, 0x02, 0xb5, 0xa9, 0xbd, 0xd5, 0xa5, 0x0c, 0xfe, 0x4d, 0x3a,
	0x8f, 0x84, 0x3f, 0x66, 0x7b, 0x25, 0xe2, 0x86, 0xcd, 0x56, 0x28, 0x2a, 0xab, 0x3d, 0x8a, 0x8d,
	0x5b, 0xec, 0xb7, 0xfc, 0x09, 0xa6, 0xf7, 0xde, 0x28, 0x32, 0xb9, 0x79, 0x6d, 0x4c, 0x20, 0xc6,
	0xe0, 0x88, 0x3e, 0x9c, 0xc9, 0x86, 0xe7, 0xc3, 0xeb, 0x49, 0x1e, 0x35, 0x3b, 0x85, 0x63, 0x5b,
	0x17, 0xe6, 0x3d, 0x1b, 0xc5, 0x61, 0xfb, 0x60, 0x29, 0x8c, 0x6c, 0x91, 0x8d, 0xe3, 0x68, 0xa3,
	0xf8, 0x09, 0xa4, 0xbb, 0xa8, 0xe0, 0xb0, 0x0e, 0x86, 0x5f, 0xc0, 0x74, 0x6e, 0xd4, 0x9a, 0xca,
	0x3f, 0xc2, 0xf9, 0x1d, 0xa4, 0x3b, 0x53, 0x7b, 0xc6, 0x66, 0x90, 0x04, 0x52, 0xd4, 0x84, 0xe8,
	0x1b, 0xe7, 0xdd, 0x6b, 0x7b, 0x6d, 0xeb, 0x25, 0x76, 0x2d, 0xa2, 0xbe, 0xf9, 0x1a, 0xc2, 0xe4,
	0x01, 0xf5, 0x63, 0xa4, 0x61, 0xcf, 0x90, 0xb4, 0x15, 0xd8, 0xa5, 0xf8, 0x1d, 0x58, 0xf4, 0x68,
	0xcf, 0xae, 0xfe, 0xb3, 0x75, 0x24, 0x83, 0x6d, 0x74, 0x5b, 0xf3, 0x70, 0x74, 0x8f, 0xf5, 0x70,
	0x74, 0x9f, 0x96, 0x0f, 0x16, 0x49, 0xfc, 0xa2, 0xdb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a,
	0x24, 0xc2, 0x3d, 0xee, 0x01, 0x00, 0x00,
}
