---
apiVersion: v1
kind: Service
metadata:
  name: tika
  namespace: default
  labels:
    name: tika
spec:
  ports:
    # the port that this service should serve on
    - name: http
      port: 9998
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: tika
