registry:
  hostname: registry
  command: -server -bootstrap -rejoin -log-level err
  image: progrium/consul:latest
  ports:
  - "8300:8300"
  - "8400:8400"
  - "8500:8500"
  - "8600:53/udp"

web:
  command: --registry_address=registry:8500 --register_interval=5 --register_ttl=10 web
  image: microhq/micro
  links:
  - registry
  ports:
  - "8082:8082"

proxy:
  command: --registry_address=registry:8500 
  image: kazoup/web-proxy
  links:
  - registry
  ports:
  - "8000:8000"

static-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/static-web
  links:
  - registry

dashboard-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/dashboard-web
  links:
  - registry

analytics-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/analytics-web
  links:
  - registry

search-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/search-web
  links:
  - registry

settings-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/settings-web
  links:
  - registry

logs-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/logs-web
  links:
  - registry

docs-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/docs-web
  links:
  - registry

login-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/login-web
  links:
  - registry

wizard-web:
  command: --registry_address=registry:8500 --environment=prod
  image: kazoup/wizard-web
  links:
  - registry
