apiVersion: v1
kind: Service
metadata:
  labels:
    name: inception-service
  name: inception-service
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    name: inception-service
  type: LoadBalancer